### ISSUE TITLE
Standard WG Meeting - May 25th, 2023

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#1005]
## Date
Thursday 25 May 2023 - 10am EST / 3pm BST

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system:
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from the previous meeting (5mins)
  - #970 
- [x] Announcements (10mins)
  - FINOS Open House and Members meeting schedules: <https://finosopenhouseandmembermeet.sched.com/>
  - Context Data & Intents meeting: Thursday 8th June 9am EST / 2pm BST
    - Rethinking the governance & processes
  - Voting on the inclusion of Desktop Agent Bridging in FDC3
    - #968
  - FDC3 Workbench updated for 2.0
    - #947 
  - Other PRs recently merged:
    - #971 
    - #973 
    - #975 
    - #983 
    - #986
- Check consensus on PRs ready to be merged into [2.1 predraft](https://fdc3.finos.org/docs/next/fdc3-intro) (15 mins):
  - [x] #972 **(ready to merge)**
  - [x] #981 **(needs editor review)**
  - [ ] #982 **(needs editor review)**
  - [x] #985 **(needs editor review, to merge into #994)**
  - [ ] #987 **(needs maintainer & editor review)**
  - [x] #994 **(awaiting final additions)**
  - [x] #996
      - [x] #999 **(ready to merge)**
      - [x] #1000 🎉 **(ready to merge)**
  - [x] #1004 **(ready to merge)**
- [x] #990 (15 mins)
  - .NET issue #931
- [x] Discuss other issues still outstanding for 2.1 (5 mins)
  - [PRs needed: ![image](https://github.com/finos/FDC3/assets/1701764/b7a7f8c3-3943-4d19-97df-2bfe2a50719f)](https://github.com/finos/FDC3/issues?q=is%3Aissue+is%3Aopen+label%3Aneeds-pr)
  - Anything from the [2.1-candidates milestone](https://github.com/finos/FDC3/milestone/6) that should be included?
- [ ] AOB & Adjourn (5mins)

## Minutes
- PRs ready to be merged into [2.1 predraft](https://fdc3.finos.org/docs/next/fdc3-intro):
  - Consent received to merge:
    - #972 **(ready to merge)**
    - #999 **(ready to merge)**
    - #1000 **(ready to merge)**
    - #1004 **(ready to merge)**
  - Consent received to merge after reviews completed:
    - #981 **(needs editor review)**
    - #985 **(needs editor review, to merge into #994)**
  - Objections to merging raised:
    - #982 **(needs editor review)**
      - Several participants (@robmoffat @lspiro-Tick42 A participant from Citi) spoke up for a use-case for vendor-agnostic configuration intended for an app (rather than a Desktop Agent, as is the case with `hostManifests`).
      - It was suggested that: 
        - An API addition would be needed to retrieve the config in a vendor agnostic way
        - A better name could be applied to the element to clarify its intended use (e.g. `applicationConfig`)
        - A new issue could/should be raised to supercede the deprecation issue (#900)
  - Not checked
    - #987 **(needs maintainer & editor review)**
      - to be checked after re-reviewed by maintainers - significant changes on the day of the meeting.
    - #994 **(awaiting final additions)**
- @kriswest gave a brief overview of [PRs needed: ![image](https://github.com/finos/FDC3/assets/1701764/b7a7f8c3-3943-4d19-97df-2bfe2a50719f)](https://github.com/finos/FDC3/issues?q=is%3Aissue+is%3Aopen+label%3Aneeds-pr) and invited contribution from the community on the,.
  - Meeting participants were also asked to review the [2.1-candidates milestone](https://github.com/finos/FDC3/milestone/6) and comment on anything that they thought should be included?
- #990 
  - @robmoffat introduced the issue and highlighted recent work on .NET (@bingenito), Java (@timjenkel) and Python (@chuck-adaptive) bindings produced for FDC3
    - @psmulovics indicated a willingness to migrate the .NET contribution to a FINOS repo
  - There was general consensus that other language bindings for FDC3 should exist
    - @rikoe remarked that it would be useful if FDC3 could be described in a language agnostic way with something like JSONSchema (although that, unfortunately, does not support function signatures) and that adding other languages will increase the maintenance burden for FDC
  - There was discussion of where language bindings should go
    - @kriswest Language bindings != implementations, which should always be outside of FDC3
    - @kriswest You'd likely want Nuget/Maven/whatever python uses packages for the interfaces or types supporting each binding
      - The FDC3 maintainer team should be/may need to be expanded to help keep these up-to-date
      - Firms wishing to contribute or adopt standardized bindings for particular languages should consider putting someone forward to maintain them if possible.
    - @rikoe We could move the Typescript sources out of the main FDC3 repo while doing this, it would make sense for each language to have its own repo.
      - @kriswest although it would be useful to keep documentation together in one place for maintenance purposes
      - @kriswest reminded the group about @bingenito's past comment that bringing in and maintaining other language bindings would help 'keep us honest' by avoiding typescript specific constructs that are hard to replicate in other languages (e.g. union types in function signatures)  
  - The end of the meeting curtailed discussion, which should continue at the next meeting
      
## Action Items
- [x] Maintainers and Editor to complete outstanding reviews
- [x] @kriswest merge approved PRs (when necessary reviews are competed)
- [x] @kriswest raise a new issue for replacing customConfig/making it retrievable via API/renaming it.
- [x] @kriswest add #987 to next meeting agenda
- [ ] @kriswest add #990 to next/a future meeting agenda

Rolled over from previous meetings:
- [ ] @kriswest Open an email vote on the inclusion of Desktop Agent Bridging as part of the FDC3 Standard
- [ ] #931 
   - Review of the proposed .NET interfaces by firms that will benefit from them is needed - along with a commitment to help with the update of the FDC3 documentation to include them.
- [ ] @kriswest Refer questions about the need for more 'authentication' in FDC3 to FDC3 for Web Browsers group
    - referred but not yet discussed
- [ ] @kriswest @nkolba @pierreneu to work on proposals/PRs demonstrating possible solutions to #829. These should include example use-cases demonstrating the need for and utility of the revision
- [ ] @finos/fdc3-maintainers to investigate adding code coverage scanning to repo and to propose a unit testing policy/raise a PR to add to governance and resolve #832.
- [ ] @kriswest or volunteer: raise PR to resolve #719 
  - Add optional/recommended API endpoints for /intents and /contexts to the appD API.

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by novavi** [comment]
Derek Novavi / S&P Global

**Comment by robmoffat** [comment]
Rob / FINOS 🐈‍⬛

**Comment by mattjamieson** [comment]
Matt / WhiteDog

**Comment by kriswest** [comment]
Kris West / Finsemble 🚀

**Comment by tpina** [comment]
Tiago Pina / Finsemble

**Comment by rikoe** [comment]
Riko Eksteen / Adaptive
