### ISSUE TITLE
Standard WG Meeting - June 27th, 2024

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#1238]
## Date
Thursday 27th June 2024 - 10am (US eastern timezone EDT) / 3pm (London, BST)

### Zoom info
- **[Join Zoom Meeting](https://zoom.us/j/96940294948?pwd=SjFibVdiN25QSWxva3FqRHY2RUFCdz09)**
- **Meeting ID:** 969 4029 4948
- **Passcode:** 636931
- **Dial-in:**
    | Country      | International Dial-in | Toll-free Dial-in |
    | :---        | :---        | :---        |
    | **US** | [+1 929 205 6099 (New York)](tel:+19292056099) | [877 853 5247](tel:8778535247) |
    | **UK** | [+44 330 088 5830](tel:+443300885830) | [0800 031 5717](tel:08000315717) |
    | **France** | [+33 1 8699 5831](tel:+33186995831) | [0 800 940 415](tel:0800940415) 
    | Find your local number | <https://zoom.us/u/ad2WVnBzb8> | |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

 ## Participation Requirements

 **Note:** Meeting participants are expected to accept the terms of the FDC3 license (Community Specification License), understand the governance process and have a CLA in place.  

 Please click the following links at the start of the meeting if you have not done so previously.

 - [View the CSL](https://raw.githubusercontent.com/finos/FDC3/main/LICENSE.md)
 - [View the GOVERNANCE of the Project](https://github.com/finos/FDC3/blob/main/GOVERNANCE.md)
 - [Click here to start a PR](https://github.com/finos/FDC3/edit/main/NOTICES.md). 
   - Edit the page to add your details.
   - Hit the save button.
   - Click "Create Pull Request".
   - Click "Accept" on the EasyCLA dialog in the PR's discussion section.
 - [Click here to send email to become a voting participant on the FDC3 Project](mailto:fdc3-participants+subscribe@finos.org?subject=Please%20enroll%20me%20as%20an%20FDC3%20Standards%20Participant&amp;body=HI%2C%20my%20name%20is%20%3CFirstName%20LastName%3E%20and%20I'd%20like%20to%20formally%20participate%20to%20the%20FDC3%20standard%20process.%20I%20plan%20to%20contribute%20as%20%3Cindividual%7Con%20behalf%20of%20organizationName%3E%20and%20I%20have%20reviewed%20the%20policies%20described%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmain%2FGOVERNANCE.md%20and%20read%20the%20license%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmain%2FLICENSE%20.%20Thank%20you!")

 ## Tracking Attendance

 **Note:** Meeting participants are expected to _add a comment to this GitHub issue_ in order that we can track attendance of FDC3 project meetings.  Please do this at the start of the meeting.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - [x] #1215
- [x] Minor project infrastructure PRs
- [x] Updated proposal for #1197
- [x] AOB
  - Updates from Discussion group meetings
  - Contribution opportunities (issues in need of a PR) (5mins):
    - #564
    - #591
    - #674
    - #719 
    - #1001
    - #1006
    - #1173
    -  #1197
    - #1203
    - Get involved in the FDC3 for Web POC
    - Volunteer as an FDC3 Editor or Maintainer
  - Q&A

## Minutes
- The meeting covered a number of small maintainence PRs that are in-flight and assigned reviews to maintainers (see action items) and briefly revisited some open issue in need of PRs
- This was followed a Q&A session clarifying some of the FDC3 for the Web proposal presented at OSFF the previous day and touching on the work of the Identity and Security group.
  - A participant asked if there is work underway to represent currency pairs in FDC3 as they need to use them? They are currently inserting them into the `id.ticker` field of the fdc3.instrument type. They also stated they were considering using an alternative standard because of this.
    - @kriswest stated that there is no currently open issue on that topic, but also provide an overview of how you create one (start by opening the issue and describe your needs). As an opensource project, it's upto the participants to raise issues for additions they want and (ideally) to contribute effort to achieve them - although in this case the maintainers are likely to help - as we're part way through refining the process to contribute context types to the Standard (via docs generation from the schemas).
    - @openfin-johans provided some additional context from the original Financial objects working group on how the existing types were created.
    -  @kriswest also demonstrated the context Standard's field conventions, which reference ISO 4217 code for currencies and indicated that it should probably be updated to also cover (and standardize the format of ) currency pairs.
  - A participant asked about proprietary context types, unlikely to be relevant to anyone outside their firm and was referred to the namespacing section of the context overview https://fdc3.finos.org/docs/context/spec#namespacing 
    - Firms can create, document and govern their own types independently of the standard, the only hard requirement is that they should be javascript objects with a `type` field that has a `string` value, which should be appropriately namespaced (don't use `fdc3.` as thats for standardized types). 
  - Is FDC3 for the Web always interactive with a server?
    - @kriswest No, it uses HTML Standard APIs to achieve communication locally with a DA running in another window or frame. However, it also supports communication with an adaptor or proxy to a DA which could then be running on a server/in the cloud. I.e. it's a flexible approach and designed to support different formats of Desktop Agent.
  - A brief overview of proposals from the Identity & Security group was provided and related to the FDC3 for the Web proposal on the issue of app identity: FDC3 for the Web proposes a basic, temporary identity validation procedure based on the a set of origins detailed in an appD record or extracted from the start URL - but is expecting to adopt asymmetric authentication if/when proposed by the identity & security group (trying to avoid doubling up on similar additions).
    - There was some discussion of identity validation of an app by a DA and a DA by an app, as these are not covered by the current identity & security proposals, which seek to achieve signed communication and encrypted communication between applications via a TLS-like asymmetric cryptography approach, which will require publication of public keys (via an appD record).

## Action Items
- [x] @openfin-johans to review #1236
- [x] @mistryvinay and @finos/fdc3-maintainers to review #1233, perhaps extend to other types that need id or name docs adding.
- [x] @mistryvinay and @kriswest to arrange to meet and progress the context docs generation PR. 
- [x] @finos/fdc3-maintainers review and merge minor project infrastructure fixes
- [ ] @kriswest @hellosmithy PR to be raised for #1197
- [x] Issue to be raised for supporting currency pairs as an `id` type in `fdc3.instrument` and the context Standard's field conventions.

Rolled over:
- [ ] @bingenito & @kriswest to complete PR #1108 and submit for review - to include at least a basic version of supported platforms content (to be improved later)
- [x] @kriswest & @mistryvinay look at #1151 and consider taking over final changes (which include deleting existing context docs, hooking up script to auto-generate as part of build and making sure existing URLs do not break)
- [x] @kriswest & @julianna-ciq rework issue #1142 to reflect the other use cases and update the proposed change based on the discussion

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by novavi** [comment]
Derek Novavi / S&P Global

**Comment by paulgoldsmith** [comment]
Paul Goldsmith / Morgan Stanley

**Comment by kriswest** [comment]
Kris West / Interop.io 🚀

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony 🎵

**Comment by openfin-johans** [comment]
Johan Sandersson / Here (formerly OpenFin) 🎁

**Comment by Roaders** [comment]
Giles Roadnight / Morgan Stanley

**Comment by hughtroeger** [comment]
Hugh Troeger / FactSet
