### ISSUE TITLE
Standard WG Meeting - July 25th, 2024

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#1292]
## Date
Thursday 25th July 2024 - 10am (US eastern timezone EST) / 3pm (London, BST)

### Zoom info
- **[Join Zoom Meeting](https://zoom.us/j/96940294948?pwd=SjFibVdiN25QSWxva3FqRHY2RUFCdz09)**
- **Meeting ID:** 969 4029 4948
- **Passcode:** 636931
- **Dial-in:**
    | Country      | International Dial-in | Toll-free Dial-in |
    | :---        | :---        | :---        |
    | **US** | [+1 929 205 6099 (New York)](tel:+19292056099) | [877 853 5247](tel:8778535247) |
    | **UK** | [+44 330 088 5830](tel:+443300885830) | [0800 031 5717](tel:08000315717) |
    | **France** | [+33 1 8699 5831](tel:+33186995831) | [0 800 940 415](tel:0800940415) 
    | Find your local number | <https://zoom.us/u/ad2WVnBzb8> | |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

 ## Participation Requirements

 **Note:** Meeting participants are expected to accept the terms of the FDC3 license (Community Specification License), understand the governance process and have a CLA in place.  

 Please click the following links at the start of the meeting if you have not done so previously.

 - [View the CSL](https://github.com/finos/FDC3/blob/main/LICENSE.md)
 - [View the GOVERNANCE of the Project](https://github.com/finos/FDC3/blob/main/GOVERNANCE.md)
 - [Click here to start a PR](https://github.com/finos/FDC3/edit/main/NOTICES.md). 
   - Edit the page to add your details.
   - Hit the save button.
   - Click "Create Pull Request".
   - Click "Accept" on the EasyCLA dialog in the PR's discussion section.
 - [Click here to send email to become a voting participant on the FDC3 Project](mailto:fdc3-participants+subscribe@finos.org?subject=Please%20enroll%20me%20as%20an%20FDC3%20Standards%20Participant&amp;body=HI%2C%20my%20name%20is%20%3CFirstName%20LastName%3E%20and%20I'd%20like%20to%20formally%20participate%20to%20the%20FDC3%20standard%20process.%20I%20plan%20to%20contribute%20as%20%3Cindividual%7Con%20behalf%20of%20organizationName%3E%20and%20I%20have%20reviewed%20the%20policies%20described%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmain%2FGOVERNANCE.md%20and%20read%20the%20license%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmain%2FLICENSE%20.%20Thank%20you!")

 ## Tracking Attendance

 **Note:** Meeting participants are expected to _add a comment to this GitHub issue_ in order that we can track attendance of FDC3 project meetings.  Please do this at the start of the meeting.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #1238 
- Announcements
  - Updated context documentation now generated from schemas: https://fdc3.finos.org/docs/next/context/ref/Action
    - Some outstanding work to do:
      -  #1282
  - Current state of work on FDC3 for Web 
  - Current state of work on Identity & Security
- [x] #1265
- [x] #1290 
- [x] #1291
- [x] (if time) #1250 & #1263
- [ ] (if time) #940 
- [ ] AOB & Adjourn (5mins)

## Minutes

- #1265
  - @bingenito introduced the issue and explained how inconsistent use camel-case complicates code in .NET for handling the enums. 
  - There as a general consensus that we should not change the existing TransactionResult context at this time, however, it might be helpful to add a note about consistent casing of enumerated values in the API and Context docs to help guide reviewers in preventing additional issues in the future
  - @bingenito to create a PR to add the advice to the docs
- #1290
  - @julianna-ciq introduced the issue which has been updated since the initial discussion and there was discussion of the use case and proposed solution.
  - @kriswest checked and received unanimous consensus that the participants recognized the importance of the use case and that a solution should be provided.
  - There was some discussion of the placement of the `traceid` field as it is metadata about the context message. 
    - @kriswest pointed out that there are other proposals on the way (notably from the Identity & Security group) that wish to add metadata to context messages and that it might be better to keep metadata properties to a `metadata` element in the context. There was some discussion of prior conversations about wanting to avoid confusion with the ContextMetadata object that may be returned with context and intent messages.
    - @Davidhanson90 indicated a dislike for including metadata inside the context message.
    - In response, @kriswest flagged similar feedback from past FDC3 maintainers on the prior version of this issue - and that he recognized that this is an unusual thing to do in the field of Information Retrieval. However, there is also strong resistance to creating additional optional parameters on functions such as `fdc3.broadcast` and `fdc3.raiseIntent` as this also rapidly adds complexity to the API. Adding an element to the context object for metadata is, in this case, significantly simpler.
    - @kriswest offered to withhold consensus on the proposal until @Davidhanson90 and @julianna-ciq have a chance to meet and look at other options before we discuss the topic again.
    - It was noted that we need a decision on style in order to raise the proposals from the Identity & Security group.
- #1291 
  - There was only time for a brief introduction to this issue. Which included comments from @openfin-johans on the issue itself.
  - @bingenito and @novavi to invite input from others at their respective firms and @kriswest to raise the topic with the FDC3 mailing list.
- #1250 & #1263
  - Not discussed in any detail due to time constraints - @kriswest wished to flag the issue to the community as it will require FDC3 API additions to solve, which are included in the proposal. The proposal will be brought to a future meeting for deeper disucssion.
- #940 
  - Not discussed due to time constraints - to be brought to a future meeting

## Action Items
- [ ] @bingenito create a PR to add the advice about consistent use of pascal case in enums in the API ([implementation language](https://fdc3.finos.org/docs/next/api/spec#implementation-language) and context docs ([The Context Interface](https://fdc3.finos.org/docs/next/context/spec#avoid-union-types--composition-of-primitive-types) section after advice on union types).
- [ ] @julianna-ciq and @Davidhanson90 to meet and discuss #1290 before asking @kriswest to include the issue in a future meeting agenda.
- [x] @bingenito and @novavi to invite input on #1291 from others at their respective firms and @kriswest to raise the topic with the FDC3 mailing list.
- [x] @kriswest navigate #1250, #1263 and #940 into a future meeting agenda

Rolled over:
- [ ] @kriswest @hellosmithy PR to be raised for #1197
- [x] @bingenito & @kriswest to complete PR #1108 and submit for review - to include at least a basic version of supported platforms content (to be improved later)

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by bingenito** [comment]
Brian Ingenito / Morgan Stanley

**Comment by paulgoldsmith** [comment]
Paul Goldsmith / Morgan Stanley

**Comment by hughtroeger** [comment]
Hugh Troeger / FactSet

**Comment by kriswest** [comment]
Kris West / interop.io 🚀

**Comment by Roaders** [comment]
Giles Roadnight / Morgan Stanley 🧔

**Comment by Davidhanson90** [comment]
David Hanson / Morgan Stanley

**Comment by pvoznyuk** [comment]
Pavlo Vozniuk / RBC CM

**Comment by robmoffat** [comment]
Rob Moffat / FINOS 👾

**Comment by julianna-ciq** [comment]
Julianna Langston / interop.io
