### ISSUE TITLE
Standard WG Meeting - September 26th, 2024

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#1364]
## Date
Thursday 26th September 2024 - 10am (US eastern timezone EDT) / 3pm (London, BST)

### Zoom info
- **[Join Zoom Meeting](https://zoom.us/j/96940294948?pwd=SjFibVdiN25QSWxva3FqRHY2RUFCdz09)**
- **Meeting ID:** 969 4029 4948
- **Passcode:** 636931
- **Dial-in:**
    | Country      | International Dial-in | Toll-free Dial-in |
    | :---        | :---        | :---        |
    | **US** | [+1 929 205 6099 (New York)](tel:+19292056099) | [877 853 5247](tel:8778535247) |
    | **UK** | [+44 330 088 5830](tel:+443300885830) | [0800 031 5717](tel:08000315717) |
    | **France** | [+33 1 8699 5831](tel:+33186995831) | [0 800 940 415](tel:0800940415) 
    | Find your local number | <https://zoom.us/u/ad2WVnBzb8> | |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

 ## Participation Requirements

 **Note:** Meeting participants are expected to accept the terms of the FDC3 license (Community Specification License), understand the governance process and have a CLA in place.  

 Please click the following links at the start of the meeting if you have not done so previously.

 - [View the CSL](https://github.com/finos/FDC3/blob/main/LICENSE.md)
 - [View the GOVERNANCE of the Project](https://github.com/finos/FDC3/blob/main/GOVERNANCE.md)
 - [Click here to start a PR](https://github.com/finos/FDC3/edit/main/NOTICES.md). 
   - Edit the page to add your details.
   - Hit the save button.
   - Click "Create Pull Request".
   - Click "Accept" on the EasyCLA dialog in the PR's discussion section.
 - [Click here to send email to become a voting participant on the FDC3 Project](mailto:fdc3-participants+subscribe@finos.org?subject=Please%20enroll%20me%20as%20an%20FDC3%20Standards%20Participant&amp;body=HI%2C%20my%20name%20is%20%3CFirstName%20LastName%3E%20and%20I'd%20like%20to%20formally%20participate%20to%20the%20FDC3%20standard%20process.%20I%20plan%20to%20contribute%20as%20%3Cindividual%7Con%20behalf%20of%20organizationName%3E%20and%20I%20have%20reviewed%20the%20policies%20described%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmain%2FGOVERNANCE.md%20and%20read%20the%20license%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmain%2FLICENSE%20.%20Thank%20you!")

 ## Tracking Attendance

 **Note:** Meeting participants are expected to _add a comment to this GitHub issue_ in order that we can track attendance of FDC3 project meetings.  Please do this at the start of the meeting.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #1317
- [x] Announcements: OSFF presentations (5mins)
- [x] Proposal to include FDC3 for the Web in the FDC3 2.2 draft as [@experimental](https://fdc3.finos.org/docs/next/fdc3-compliance#experimental-features) (15 mins)
  - #896
    - #1191
- [x] Check consensus on the inclusion of several smaller issues in 2.2 (10mins):    
  - #591 
  - #1351
  - #1255 
  - #1282
  - #1353
- [x] Proposal to close the scope for FDC3 2.2 and push other open issues and PRs to FDC3 2.3 (10mins)
  - [Proposed 2.2 scope](https://github.com/finos/FDC3/issues?q=milestone%3A%222.2+candidates%22)
  - [2.3 candidates](https://github.com/finos/FDC3/issues?q=is%3Aopen+is%3Aissue+milestone%3A%222.3+candidates%22+-label%3Ameeting)
  - [Issues with no milestone](https://github.com/finos/FDC3/issues?q=is%3Aopen+is%3Aissue+-label%3Ameeting+no%3Amilestone)
- Adjourn

## Minutes
- Incomplete action items from the previous meeting were rolled over
- @kriswest Asked the Standards Working Group participants if there was consensus for the inclusion of the FDC3 for the Web proposal in the FDC3 2.2 scope as @experimental and for the PR (#1191) to be merged once it clears review by FDC3's editor.
  - Consensus was given (unanimous, with several participants speaking for the proposal and the and the rigour of the process used to create it) 
- @kriswest Also asked if there was consensus for the inclusion of the set of issues detailed in the agenda to be included in the FDC3 2.2 scope.
  - There was consensus that the following issues   be included:
    - #591
    - #1255 
    - #1282
    - #1353
  - An objection was recorded to the following issue, with the maintainers requested to review alternative options (as CommonJS is still in use in some places in front-end apps):
    - #1351
- @kriswest Asked if there was consensus on closing the resulting 2.2 scope (and provided an overview of the proposed scope, a possible scope for 2.3 and open issues not in any proposed scope), allowing the maintainers to focus on the delivery of that scope, with any further issues being bumped to FDC3 2.3 or beyond).
  - There was consensus that we should adopt the proposed 2.2 scope.

## Action Items
- [ ] @finos/fdc3-editors and @finos/fdc3-maintainers to complete review of #1191 and merge into the current (FDC3 2.2) draft
- [ ] FDC3 maintainers and interested contributors to revisit #1351 as it should continue to be possible to publish a combined CommonJS and ES6 module, or to raise an alternative proposal.
- [x] @kriswest to update milestones to finalize 2.2 scope and @finos/fdc3-maintainers and @finos/fdc3-editors to work towards delivering 2.2

Rolled over:
- [ ] **All** encourage review of the fdc3-dtnet 2.1 update:
   - issue: https://github.com/finos/fdc3-dotnet/issues/74
   - PR: https://github.com/finos/fdc3-dotnet/pull/141
- [ ] @kriswest Update the proposal for #1250 to include a tear down function for 'subAgents'.
- [ ] @julianna-ciq and @Davidhanson90 to meet and discuss the alternative proposal to resolve #1290 posted @kriswest as a comment on the issue, before it is debated at next month's meeting
- [ ] @bingenito create a PR to add the advice about consistent use of pascal case in enums in the API ([implementation language](https://fdc3.finos.org/docs/next/api/spec#implementation-language) and context docs ([The Context Interface](https://fdc3.finos.org/docs/next/context/spec#avoid-union-types--composition-of-primitive-types) section after advice on union types).
- [x] @kriswest @hellosmithy PR to be raised for #1197

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by novavi** [comment]
Derek Novavi / S&P Global

**Comment by mistryvinay** [comment]
Vinay Mistry @ Symphony 🎵

**Comment by kriswest** [comment]
Kris West / interop.io 🚀

**Comment by Roaders** [comment]
Giles Roadnight / Morgan Stanley

**Comment by gilesstevenson** [comment]
Giles Stevenson / Here (formerly OpenFin)

**Comment by robmoffat** [comment]
Rob Moffat / FINOS

**Comment by watson-ew** [comment]
Chris Watson / Elgin White 👋

**Comment by symphony-jean-michael** [comment]
Jean-Michael Legait / Symphony

**Comment by Davidhanson90** [comment]
David Hanson -  Morgan Stanley 🚀

**Comment by paulgoldsmith** [comment]
Paul Goldsmith / Morgan Stanley

**Comment by hughtroeger** [comment]
Hugh Troeger / FactSet
