### ISSUE TITLE
Standard WG Meeting - October 24th, 2024

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#1400]
## Date
Thursday 24th October 2024 - 10am (US eastern timezone EDT) / 3pm (London, BST)

### Zoom info
- **[Join Zoom Meeting](https://zoom.us/j/96940294948?pwd=SjFibVdiN25QSWxva3FqRHY2RUFCdz09)**
- **Meeting ID:** 969 4029 4948
- **Passcode:** 636931
- **Dial-in:**
    | Country      | International Dial-in | Toll-free Dial-in |
    | :---        | :---        | :---        |
    | **US** | [+1 929 205 6099 (New York)](tel:+19292056099) | [877 853 5247](tel:8778535247) |
    | **UK** | [+44 330 088 5830](tel:+443300885830) | [0800 031 5717](tel:08000315717) |
    | **France** | [+33 1 8699 5831](tel:+33186995831) | [0 800 940 415](tel:0800940415) 
    | Find your local number | <https://zoom.us/u/ad2WVnBzb8> | |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

 ## Participation Requirements

 **Note:** Meeting participants are expected to accept the terms of the FDC3 license (Community Specification License), understand the governance process and have a CLA in place.  

 Please click the following links at the start of the meeting if you have not done so previously.

 - [View the CSL](https://github.com/finos/FDC3/blob/main/LICENSE.md)
 - [View the GOVERNANCE of the Project](https://github.com/finos/FDC3/blob/main/GOVERNANCE.md)
 - [Click here to start a PR](https://github.com/finos/FDC3/edit/main/NOTICES.md). 
   - Edit the page to add your details.
   - Hit the save button.
   - Click "Create Pull Request".
   - Click "Accept" on the EasyCLA dialog in the PR's discussion section.
 - [Click here to send email to become a voting participant on the FDC3 Project](mailto:fdc3-participants+subscribe@finos.org?subject=Please%20enroll%20me%20as%20an%20FDC3%20Standards%20Participant&amp;body=HI%2C%20my%20name%20is%20%3CFirstName%20LastName%3E%20and%20I'd%20like%20to%20formally%20participate%20to%20the%20FDC3%20standard%20process.%20I%20plan%20to%20contribute%20as%20%3Cindividual%7Con%20behalf%20of%20organizationName%3E%20and%20I%20have%20reviewed%20the%20policies%20described%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmain%2FGOVERNANCE.md%20and%20read%20the%20license%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmain%2FLICENSE%20.%20Thank%20you!")

 ## Tracking Attendance

 **Note:** Meeting participants are expected to _add a comment to this GitHub issue_ in order that we can track attendance of FDC3 project meetings.  Please do this at the start of the meeting.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #1364 
- [x] Proposal of a new FDC3 Editor (Derek Novavi @novavi) and new FDC3 maintainer (Lizaveta Kemereva @kemerava) 
- [x] #1385 
- [x] Conformance test definitions for FDC3 2.2
- [x] Discussion of issues in scope for FDC3 2.3, e.g.:
  - #1197
  - #1291
  - #1290 
  - #1373 & #1374
  - #1382
  - #1390
  - [See all candidate issues](https://github.com/finos/FDC3/issues?q=is%3Aopen+is%3Aissue+milestone%3A%222.3+candidates%22)
- [x] AOB & Adjourn (5mins)

## Minutes
- **Proposal of a new FDC3 Editor (Derek Novavi @novavi) and new FDC3 maintainer (Lizaveta Kemereva @kemerava)** 
  - @kriswest proposed @novavi as an FDC3 Editor and received consent from the meeting to appoint
  - @kriswest proposed @kemerava as an FDC3 maintainer  and received consent from the meeting to appoint
- #1385
  - The issue was reviewed and highlighted as an omission from the fdc3-for-web PR, one that was very much intended to be included as a core part of the intended changes - but also as a historical error in earlier FDC3 versions (as it has never been the case that window.fdc3 is always set, or we would not have needed to define an `fdc3Ready` event (see https://fdc3.finos.org/docs/api/spec#api-access)
    - @kriswest requested and received consent of the meeting to add the PR from @Roaders to the fdc3-for-web branch before it is merged - @Roaders was thanked for pointing out this omission!
    - Some knock-on effects of the change in _methods.ts_ were discussed (e.g. the need for null checks/typeguards)
    - There was additional discussion of the purpose of the functions in _methods.ts_ and whether they should be deprecated (`fdc3Ready` is superseded by `getAgent`, enabling es6-style imports of functions is not adding much, it can also be achieved via destructuring with one line of code etc.)
      - There was consensus that these functions should be deprecated in 2.2 and removed in a future major version (FDC3 3.0).
- **Conformance test definitions for FDC3 2.2**
  - @kriswest demonstrated where conformance test definitions live in the Standard's repo and asked that PR authors add new test definitions to their PRs where necessary - it was agreed that details on doing so should be added to the proposed PR template. 
    - The conformance test definitions do not appear in the Standard's website. However, at least two participating firms have recently been referred to the test definitions to better understand the Standard, hence, it was proposed that they should be accessible through the website in future. 
- @kriswest provided a short review of issues proposed for the FDC3 2.3 scope, how to see the list ([see all candidate issues](https://github.com/finos/FDC3/issues?q=is%3Aopen+is%3Aissue+milestone%3A%222.3+candidates%22)) and asked that participants flag to him or fdc3-maintainers@finos.org or comment directly on any issues that they would like to see discussed at a future meeting.
  - The list does not yet include issues or PRs relating to the work of the Identity and Threat Modelling discussion group, which expects to include some key additions that have already been explored by firms (as demonstrated at OSFF https://www.youtube.com/watch?v=KLe0pdeCE-0) @Yannick-Malins @paulgoldsmith 

## Action Items
- [x] @kriswest to propose a Pull request template, to include review criteria for the FDC3 repository, which should include checking that:
  - a CHANGELOG.md entry was included
  - any necessary additions needed to conformance test definitions were made
  - changes applied to docs were also applied to TS files and schemas where necessary
  - code generation functions were run and results added to the PR for any schema changes
  - etc.
- [x] @robmoffat / FINOS to add @novavi and @kemerava to the fdc3-editors and fdc3-maintainers teams (respectively), the fdc3-maintainers google group, and fdc3-maintainers slack channel etc.
- [x] @kriswest and other PR authors to add text definitions of conformance test cases to their PRs (https://github.com/finos/FDC3/tree/main/toolbox/fdc3-conformance)
- [x] @kriswest to raise an issue to deprecate the `fdc3Ready` function and es6-style functions from methods.ts as superseded by `getAgent`
- [x] @bingenito to set up a meeting to walkthrough the fdc3-dotnet 2.1 update PR and facilitate review
  - issue: https://github.com/finos/fdc3-dotnet/issues/74
  - PR: https://github.com/finos/fdc3-dotnet/pull/141

Rolled over from previous meetings:
- [x] @finos/fdc3-editors and @finos/fdc3-maintainers to complete review of #1191 and merge into the current (FDC3 2.2) draft
- [ ] FDC3 maintainers and interested contributors to revisit #1351 as it should continue to be possible to publish a combined CommonJS and ES6 module, or to raise an alternative proposal.
- [x] **All** encourage review of the fdc3-dotnet 2.1 update:
  - issue: https://github.com/finos/fdc3-dotnet/issues/74
  - PR: https://github.com/finos/fdc3-dotnet/pull/141
- [ ] @finos/fdc3-maintainers Update the proposal for #1250 to include a tear-down function for 'subAgents'.
- [ ] @kriswest add #1290 to a future meeting agenda to determine what solution to select for the 2.3 scope
- [ ] @bingenito create an issue and PR to add the advice about consistent use of pascal case in enums in the API ([implementation language](https://fdc3.finos.org/docs/next/api/spec#implementation-language) and context docs ([The Context Interface](https://fdc3.finos.org/docs/next/context/spec#avoid-union-types--composition-of-primitive-types) section after advice on union types).

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by paulgoldsmith** [comment]
Paul Goldsmith / Morgan Stanley

**Comment by novavi** [comment]
Derek Novavi / S&P Global

**Comment by Roaders** [comment]
Giles Roadnight / Morgan Stanley

**Comment by kriswest** [comment]
Kris West / interop.io 🚀

**Comment by robmoffat** [comment]
Rob Moffat / FINOS 🔨

**Comment by kemerava** [comment]
Lizaveta (Elizabeth) Kemerava / Blackrock

**Comment by VedPrakashJha-FMR** [comment]
Ved Jha / Fidelity Investments

**Comment by bingenito** [comment]
Brian Ingenito/ Morgan Stanley

**Comment by watson-ew** [comment]
Chris Watson / Elgin White 👋
