### ISSUE TITLE
Standard WG Meeting - December 5th, 2024

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#1458]
## Date
Thursday 5th December 2024 - 10am (US eastern timezone EST) / 3pm (London, GMT)

### Zoom info
- **[Join Zoom Meeting](https://zoom.us/j/96940294948?pwd=SjFibVdiN25QSWxva3FqRHY2RUFCdz09)**
- **Meeting ID:** 969 4029 4948
- **Passcode:** 636931
- **Dial-in:**
    | Country      | International Dial-in | Toll-free Dial-in |
    | :---        | :---        | :---        |
    | **US** | [+1 929 205 6099 (New York)](tel:+19292056099) | [877 853 5247](tel:8778535247) |
    | **UK** | [+44 330 088 5830](tel:+443300885830) | [0800 031 5717](tel:08000315717) |
    | **France** | [+33 1 8699 5831](tel:+33186995831) | [0 800 940 415](tel:0800940415) 
    | Find your local number | <https://zoom.us/u/ad2WVnBzb8> | |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

 ## Participation Requirements

 **Note:** Meeting participants are expected to accept the terms of the FDC3 license (Community Specification License), understand the governance process and have a CLA in place.  

 Please click the following links at the start of the meeting if you have not done so previously.

 - [View the CSL](https://github.com/finos/FDC3/blob/main/LICENSE.md)
 - [View the GOVERNANCE of the Project](https://github.com/finos/FDC3/blob/main/GOVERNANCE.md)
 - [Click here to start a PR](https://github.com/finos/FDC3/edit/main/NOTICES.md). 
   - Edit the page to add your details.
   - Hit the save button.
   - Click "Create Pull Request".
   - Click "Accept" on the EasyCLA dialog in the PR's discussion section.
 - [Click here to send email to become a voting participant on the FDC3 Project](mailto:fdc3-participants+subscribe@finos.org?subject=Please%20enroll%20me%20as%20an%20FDC3%20Standards%20Participant&amp;body=HI%2C%20my%20name%20is%20%3CFirstName%20LastName%3E%20and%20I'd%20like%20to%20formally%20participate%20to%20the%20FDC3%20standard%20process.%20I%20plan%20to%20contribute%20as%20%3Cindividual%7Con%20behalf%20of%20organizationName%3E%20and%20I%20have%20reviewed%20the%20policies%20described%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmain%2FGOVERNANCE.md%20and%20read%20the%20license%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmain%2FLICENSE%20.%20Thank%20you!")

 ## Tracking Attendance

 **Note:** Meeting participants are expected to _add a comment to this GitHub issue_ in order that we can track attendance of FDC3 project meetings.  Please do this at the start of the meeting.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #1400
- [x] Announcements and PRs under review
  - fdc3-dotnet 2.1.0 release: https://github.com/finos/fdc3-dotnet/releases/tag/v2.1.0
  - FDC3 for Web implementation progress update
  - #1417
  - #1426
  - (WIP) #1441
- [x] FDC3 for Web
  - Progress on implementation:
    - #1309
    - #1452 (help wanted!)
    - #1456
    - #1433
  - Approve small corrections to FDC3 for Web schemas: 
    - #1442
    - #1446
    - #1459
  - #1457
- [ ] Discussion of issues in scope for 2.3
  - #1419
  - #1407
  - #1390
    - #1394
  - Identity and Security proposals
  - #1339
  - Contexts
    - #1373
    - #1374
    - #1291
    - #656
  - #1250 
- [ ] AOB & Adjourn

## Minutes
- Announcements
  - fdc3-dotnet 2.1.0 release: https://github.com/finos/fdc3-dotnet/releases/tag/v2.1.0
  - @bingenito reports that .NET 2.2 work has begun
    - proposed signatures (non-intent/context) event listeners ([#1441](https://github.com/finos/FDC3/pull/1441))
    - Other work will be guided by the FDC3 [CHANGELOG](https://github.com/finos/FDC3/blob/main/CHANGELOG.md)
  - API conformance test definitions are to be added to the documentation ([#1417](https://github.com/finos/FDC3/pull/1417))
    - When adding to the API in future, PRs should ideally include any updates to conformance tests that are needed 
    - Draft 2.2 conformance test additions are open for review ([#1426](https://github.com/finos/FDC3/pull/1426))
  - FDC3 for Web Browsers implementation work is ongoing and active, a complete draft will soon be open for review and testing
    - The deprecation of the `fdc3Ready()` function from methods.ts and replacement by `getAgent()` was noted
    - ES6/Common.js: Whether to continue publishing is still an open question.
     - ES6 is still problematic when running tests with Jest ([ES6 support is experimental](https://jestjs.io/docs/ecmascript-modules)), applications with legacy builds and legacy backend systems
     - One way to proceed would be to publish separate ES6 and Common.js modules - that will provide us with statistics on usage to compare - allowing the common.js version to be retired when it is no longer in use. The mono-repo structure introduced in the fdc3-for-web-impl PRs makes that easier to do.
- FDC3 for Web Browsers 
  - Implementation work
        - Fair bit of implementation work is happening.
        - Giles is working on typescript types, type guards, validation function, better unions. This has been merged into the implementation PR.
        - Implementation is being aligned with the spec.
        - Prettier/ESLint need to be added.
        - Julianna has added reference UIs. Rob has also worked on the reference UIs.
        - The remaining work is to make this a well-documented, high-quality code base.
        - Implementers agreed that once more PRs go in (Kris'), it will be ready for code review.
        - We may not get Rob's time starting next year.
        - Upcoming: looking to recruit reviewers for the typescript code base.
          - Expect an announcement soon
        - The PR also refactors the FDC3 repository to be a monorepo to better support current and future component projects.
  - Small changes to proposed during implementation
    - The following issues/PRs were reviewed and clarifying questions were asked by participants:
      - #1442
      - #1446
      - #1459
    - Consent was requested and received for making all three proposed changes.
- FDC3 Conformance tests to be added to website
  - It is proposed in that the FDC3 Conformance test definitions (i.e. the description of the test cases to run, rather than their implementation in the [FDC3 Conformance Framework](https://github.com/finos/FDC3-conformance-framework)) should be exposed though the FDC3 website as they have recently been referred to clarify the behaviour intended in the FDC3 Standard for a number of participants but are not currently easy to find.
  - Consent was requested and received to do so by merging PR ##1417 
  - Reviews are needed on the subsequent PR to add tests covering new or refined behaviour in FDC3 2.2, as proposed:
    - #1415 
      - #1426 
- @kriswest briefly reviewed the open issues proposed for the 2.3 scope before the meeting adjourned

## Action Items
- [x] @finos/fdc3-editors and @finos/fdc3-maintainers to complete review of the following issues and merge them:
  - #1442
  - #1446
  - #1459
- [ ] @finos/fdc3-editors and @finos/fdc3-maintainers to review and merge #1426 

Rolled over from previous meetings:
- [x] FDC3 maintainers and interested contributors to revisit #1351 as it should continue to be possible to publish a combined CommonJS and ES6 module, or to raise an alternative proposal.
- [ ] @finos/fdc3-maintainers Update the proposal for #1250 to include a tear-down function for 'subAgents'.
- [ ] @kriswest add #1290 to a future meeting agenda to determine what solution to select for the 2.3 scope
- [ ] @bingenito create an issue and PR to add the advice about consistent use of pascal case in enums in the API ([implementation language](https://fdc3.finos.org/docs/next/api/spec#implementation-language) and context docs ([The Context Interface](https://fdc3.finos.org/docs/next/context/spec#avoid-union-types--composition-of-primitive-types) section after advice on union types).

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by bingenito** [comment]
Brian Ingenito / Morgan Stanley

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony 🎵

**Comment by novavi** [comment]
Derek Novavi / S&P Global

**Comment by paulgoldsmith** [comment]
Paul Goldsmith / Morgan Stanley

**Comment by julianna-ciq** [comment]
Julianna Langston / interop.io

**Comment by kriswest** [comment]
Kris West / interop.io 🚀

**Comment by pvoznyuk** [comment]
Pavlo Vozniuk / RBC CM 🦁

**Comment by watson-ew** [comment]
Chris Watson / Elgin White 👋
