### ISSUE TITLE
Standard WG Meeting - June 25th, 2020

### ISSUE THREAD

**Issue by nkolba** [finos/FDC3#212]
## Date
Thursday 25 June, 2020 - 10am EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Review action items from previous meetings (5mins)
- [ ] Proposal for creation of tooling group.  We have a number of issues (#206 - Typescript defintions, #141 - Context Validator, plus FDC3 Explained and other demo initiatives) related specifically to tooling that would be great to get more focus on.  These issues are really separate from the goals of the standard WG - so proposal is to set up a separate group to execute on tooling projects.  This wouldn't be a formal WG or another meeting, but an informal group focused on code.  (5 min)
- [ ] Strawman Intents with Data Returns.  Strawman example addressing issue #201 (20 min)
- [ ] Intents vs RPC.  A key question to resolve is should we handle data use cases through the existing intents paradigm in FDC3, or should we define a separate RPC-like API for this.  (as proposed in issue #203). (15 min)
- [ ] AOB & Adjourn (10mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system: 
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

**Comment by rikoe** [comment]
here!

**Comment by chedzoir** [comment]
Here!

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by sgd2z** [comment]
✔️

**Comment by sean-ciq** [comment]
Here

**Comment by mattjamieson** [comment]
Here!

**Comment by lspiro-Tick42** [comment]
Present

**Comment by donbasuno** [comment]
Checked

**Comment by pjbroadbent** [comment]
Here

**Comment by mpthan** [comment]
here

**Comment by aitana16** [comment]
here

**Comment by kriswest** [comment]
here

**Comment by nkolba** [comment]
here
