### ISSUE TITLE
Standard WG Meeting - July 23rd, 2020

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#229]
## Date
Thursday 23 July 2020 MMM 2020 - 10am EST / 3pm GMT

## Attendees
Please comment on this issue to help us track attendance.

Untracked attendees:
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [x] Convene & roll call (5mins)
- [x] Review action items from previous meetings (5mins)
- [x] #177 - Generic list context schema (10mins)
- [ ] #213 - Context equivalent of RaiseIntent (15mins)
- [x] #227 - Representing FX currency pairs (15mins)
- [x] AOB & Adjourn (10mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system: 
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

**Comment by zhenyakovalyov** [comment]
here!

**Comment by kriswest** [comment]
here!

**Comment by rikoe** [comment]
present

**Comment by nkolba** [comment]
here

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by brooklynrob** [comment]
here

**Comment by chedzoir** [comment]
Here Sir!

**Comment by lspiro-Tick42** [comment]
here

**Comment by tarsillon1** [comment]
here

**Comment by pjbroadbent** [comment]
here

**Comment by mattjamieson** [comment]
👍

**Comment by donbasuno** [comment]
I passed out at 31 flavours last night

**Comment by sgd2z** [comment]
✔

**Comment by sanjaynagpal** [comment]
here

**Comment by aitana16** [comment]
here
