### ISSUE TITLE
Standard WG Meeting - Feb 25, 2021

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#325]
## Date
Thursday 25 Feb 2021 - 10am EST /  3pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system: 
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (5 mins)
- [x] Review actions from previous meeting #303 (5 mins)
- [x] 1.2 release outstanding items (10 mins)
- [x] PR #324: API to retrieve FDC3 version and provider (10 mins)
- [x] Issue #308: Remove concept of global channel in future release (10 mins)
- [x] Issue #326: Marking items as deprecated items as part of FDC3 1.2 (10 mins)
- [ ] AOB & Adjourn (10mins)

## Decisions Made
- ...

## Action Items
- [ ] ...

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

**Comment by agitana** [comment]
hello!

**Comment by zhenyakovalyov** [comment]
here

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by lspiro-Tick42** [comment]
Here

**Comment by rikoe** [comment]
hi

**Comment by jberes** [comment]
Hi

**Comment by kriswest** [comment]
🚀

**Comment by donbasuno** [comment]
alive and kicking

**Comment by tarsillon1** [comment]
Here!

**Comment by sgd2z** [comment]
✔
