### ISSUE TITLE
Standard WG Meeting - May 27, 2021

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#394]
## Date
Thursday 27 May 2021 - 10am EST / 3pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system:
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
- [x] Announcements (5 mins)
  - [x] Community Specification license
  - [x] new lead maintainer role
- [x] The FDC3 charter (5-10 mins)
- [x] Review new issues (15 mins)
- [x] Setting up Special Interest Groups (SIG) (15 mins)
  - [x] Channels, Feeds & Transactions
  - [ ] App instances
  - [ ] AppD (is one needed?) and any other proposals
- [x] AOB & Adjourn (5mins)

## Decisions Made
- The FDC3 Charter is vague on the definition of interoperability and hence scope can be hard to define precisely
- Notifications #387 needs business use-cases defined that explain why FDC3 should include explicit support for notifications (rather than allowing it to be supported via existing concepts such as intents, without standardisation)
- (silent consent) Special Interest Groups to be renamed to avoid clash with existing FINOS terminology -> Discussion Group
- (silent consent) Discussion Groups to be: 
  - organized by a member of the FDC3 PMC where possible
  -  to be open to anyone that can attend a Standards Working Group meeting 
  - to be promoted via the FDC3 mailing list

## Action Items
- [ ] #314 PR for the vendor-independent manifest to be submitted   @ggeorgievx 
- [x] #387 use-cases to be defined and case to be made for standardization for discussion at a future meeting (@kriswest, @lspiro-Tick42, @jberes )
- [ ] #386 saving and restoring state: use-cases to be refined and case to be made for standardization for discussion at a future meeting
- [x] @kriswest to organize a "Channels, Feeds & Transactions" discussion group 
  - to meet mid-June
  - explanation of scope and proposed meeting times to be emailed to FDC3 mailing list

## Untracked attendees
- Full name, Affiliation, GitHub username

**Comment by lspiro-Tick42** [comment]
Here

**Comment by pbaize** [comment]
Here

**Comment by agitana** [comment]
hello

**Comment by kriswest** [comment]
Here 👍

**Comment by rikoe** [comment]
Present

**Comment by tarsillon1** [comment]
Here

**Comment by mattjamieson** [comment]
:wave:

**Comment by jberes** [comment]
Here

**Comment by jgavronsky** [comment]
Jane here

**Comment by dominicgifford** [comment]
here, eventually

**Comment by kriswest** [comment]
**Draft** minutes posted
