### ISSUE TITLE
Standard WG Meeting - June 24, 2021

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#408]
## Date
Thursday 24 June 2021 - 10am EST / 3pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system:
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call, review meeting notices (5mins)
- [ ] Review [action items from previous meeting](https://github.com/finos/FDC3/issues/394) (5mins)
- [ ] #399 Channel Feeds & Transactions discussion group next week (<5mins)
- [ ] #387 Notifications (20mins)
- [ ] Review App Directory issues (20mins)
  - [ ] Quick summary fo each [AppD issue](https://github.com/finos/FDC3/issues?q=is%3Aissue+is%3Aopen+label%3Aapp-directory)
  - [ ] Arrange indicative vote on issues -> move to PRs
- [ ] (If time) #405 / #406 Fix discrepency in definition of Context type in 1.2 API documentation
- [ ] AOB & Adjourn (5mins)

## Decisions Made
- #387 (Silent consent) Notifications were discussed, defer further discussion until there is further input on the issue and/or an alternative proposal to consider

## Action Items
- [ ] #314 (Carried over from the previous meeting) PR for the vendor-independent manifest to be submitted   @ggeorgievx
- [ ] #386 (Carried over from the previous meeting) Saving and restoring state: use-cases to be refined and case to be made for standardization for discussion at a future meeting @lspiro-Tick42 
- [ ] #387 An alternative proposal based on raising an Intent to submit a notification is desired (no volunteer came forward to create one) - a standardized context describing a notification is already proposed.
- [x] Check with FINOS how to handle situations where a firm desires that the group NOT discuss a particular issue because they anticipate working on a similar feature in future and potentially going in a different direction @Julia-Ritter 
- [ ] #413 Everyone: please indicate interest (or disinterest) in the acceptance of issues already raised relating to the app-directory
- [ ] #247 & #371 make clearer (in the issue and proposal/JSON itself) what type of channels the data refers to (one issue refers to system channels, the other app channels) @kriswest 

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by pbaize** [comment]
Present

**Comment by dominicgifford** [comment]
Here

**Comment by agitana** [comment]
hi! Aitana Myohl / FINOS

**Comment by rikoe** [comment]
Here

**Comment by kriswest** [comment]
Here

**Comment by donbasuno** [comment]
🎁

**Comment by openfin-gavin** [comment]
Here

**Comment by jgavronsky** [comment]
Jane here

**Comment by tjpassaro** [comment]
Here

**Comment by Smith-Stephen-A** [comment]
Stephen Here

**Comment by Julia-Ritter** [comment]
Julia here

**Comment by Julia-Ritter** [comment]
Thanks all!
