### ISSUE TITLE
Channels, Feeds & Transactions Discussion group meeting 29 July 2021

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#436]
## Group overview
There are currently ~11~ ~10~ 12 open issues in the FDC3 repository, under consideration for the 2.0 release, that relate to the existing concept of channels (both the 'system channels' used via the desktop agent API, and 'app channels' interacted with through the Channels API) and new concepts we've discussed introducing: transactions (a standardized way to make a request and receive a response back) and feeds (a standardized way to request a stream of data, such as a pricing stream).

### Relevant issue tags
Current open issues that relate to the above concepts with the label: 
[![](https://user-images.githubusercontent.com/1701764/120999635-422ebd00-c781-11eb-8033-7f6ff251605b.png)](https://github.com/finos/FDC3/labels/channels%20feeds%20%26%20transactions)

## Meeting Date
Thursday 29 July 2021 - 9am EST / 2pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=me73c148c2a72069d2e76c3b295e95ae2)
- Meeting number: 127 111 4958
- Password: e3EeiZkzF25

*More ways to join*
- Join by video system:
   - Dial 1271114958@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number.
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 127 111 4958

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC 2.0 as a whole.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
- [x] Review (relevant) new issues raised since last meeting (45 mins)
  - [x] #430 (confirm recommendation, and firm up details)
  - [x] #431 (confirm recommendation)
  - [x] #432 (review proposal and firm up details)
  - [ ] #433 (solicit proposals for next meeting)
  - [ ] #434 (discuss) 
  - [x] is #215 still relevant?
- [ ] Agenda items for next meeting, AOB & Adjourn (5mins)

## Minutes
- #430 
  - All accept this proposal
  - Also rename joinChannel -> joinUserChannel and deprecate joinChannel
  - Create PR and add to 2.0 scope
- #431 
  - These functions are needed where an application can't adopt the Destkop Agent's UI
    - Several participants related direct experience with this in (legacy) native applications that want to use FDC3
  - Soft option preferred - make these functions optional, if we fully deprecate and they are needed we're forcing people into proprietary APIs
  - We should improve the documentation of `fdc3.addContentListener` and `fdc3.broadcast` to mention joining the channels
- #432 
  - Later proposal preferred by several participants
    - Desktop agent can resolve IntentResolution promise as soon as the intent/context is delivered to resolving app
    - Then the app that raised intent can wait on the intenthandler to resolve the promise for the data (or void)
  - Several participants are nervous about returning data from intents, which they think of as 'fire and forget'. 
  - Other participants think introducing a separate set of concepts that mirror intents, but allow the return of data would add unnecessary complexity to the standard
    - The proposed additions are optional - you do not need to wait on the promises
  - @mattjamieson to raise an alternative proposal for this issue for consideration

## Action Items
- [x] Schedule next two discussion group meeting for 12 August and 9 September - Aitana/Julia
- [ ] Raise PRs for #430 and #431 - @kriswest 
  - [ ] Raise PR to improve documentation of `fdc3.addContentListener` and `fdc3.broadcast` to mention joining channels @kriswest 
- [x] Alternative proposal for #432 - @mattjamieson 
- [x] Agenda items to roll over to next meeting:
  - [x] #433 (solicit proposals for next meeting)
  - [x] #434 (discuss) 
  - [x] is #215 still relevant?
  - [x] #432 alternative proposal

**Comment by kriswest** [comment]
🚀

**Comment by pbaize** [comment]
Present

**Comment by thorsent** [comment]
Present

**Comment by rikoe** [comment]
🎉

**Comment by mattjamieson** [comment]
:gb:

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by agitana** [comment]
Aitana Myohl / FINOS

**Comment by openfin-gavin** [comment]
here
