### ISSUE TITLE
Channels, Feeds & Transactions Discussion group meeting 9th Sept 2021

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#452]
## Group overview
There are currently 13 open issues in the FDC3 repository, under consideration for the 2.0 release, that relate to the existing concept of channels (both the 'system channels' used via the desktop agent API, and 'app channels' interacted with through the Channels API) and new concepts we've discussed introducing: transactions (a standardized way to make a request and receive a response back) and feeds (a standardized way to request a stream of data, such as a pricing stream).

### Relevant issue tags
Current open issues that relate to the above concepts with the label: 
[![](https://user-images.githubusercontent.com/1701764/120999635-422ebd00-c781-11eb-8033-7f6ff251605b.png)](https://github.com/finos/FDC3/labels/channels%20feeds%20%26%20transactions)

## Meeting Date
Thursday 9th Aug 2021 - 9am EDT / 2pm BST

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mf2940a718824a41e0747dada7d34e271)
- Meeting number: 127 494 1096
- Password: 3cqFgG7fMT2

*More ways to join*
- Join by video system:
   - Dial 1274941096@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number.
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 127 494 1096

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC 2.0 as a whole.

## Agenda
- [x] Convene & roll call, review meeting notices **(5mins)**
- [x] Review action items from previous meeting **(5mins)**
  - #444 
  - [x] Votes still open (until shortly after next SWG meeting)
    - #242 [Vote link](https://github.com/finos/FDC3/issues/242#issuecomment-878968419)
    - #301 [Vote link](https://github.com/finos/FDC3/issues/301#issuecomment-878980692)
    - #413 (multiple issues)
- [x] #434 **(20mins)**
- [x] Further work on #432 **(20mins)**
  - @thorsent @kriswest Update option 2 proposal to convert the data element in the resolution into a function, modifying raiseIntent signature
  - @pbaize alternative proposal based on wrapping existing concepts
- [x] Volunteers needed **(5mins)**
  - PR Contributors and Editors  
    - @kriswest #361 (update PR #375) 
    - @kriswest #418 (Documentation only)
    - @kriswest #426 (Documentation only) 
    - @kriswest #431 (Documentation only)
    - @mattjamieson #435 (Update methods.ts) 
    - #308 (remove deprecated content from documentation and spec)
    - #362 (minor API changes + documentation)
    - #430 (rename functions + create alias' for backwards compatibility + documentation)
    - #432 (PR(s) for final proposal(s)
    - #451 (Documentation only)
  - Reviewers needed
    - #440 
    - #437 
- [x] Next meeting agenda, AOB & Adjourn **(5mins)**
  - #433 

## Minutes
- Two issues discussed and brought to a conclusion ready to prepare PRs for the Standards Working Group to review:
  - #434 (Rapid-fire broadcast all context types you want other applications to respond to, Rather than expecting them to extract types they want)
  - #432 (preferred proposal chosen) 
- Some discussion of whether we should add support for flagging 'experimental' features in the FDC3 specification to make it clearer that such features may change in future based on industry feedback.

## Decisions Made
- #434 
  - Improve recommendations for broadcast context single vs. multiple types (for composite types) in the docs and specification
  - consensus that apps should broadcast all the types that they expect other apps to respond to (allows use of typed context listeners for filtering)
- #432 
  - consensus that the [updated 'option 2' proposal](https://github.com/finos/FDC3/issues/432#issuecomment-909425149) is workable and appropriate (if not yet proven in use) 
  - will go to PR and not back on agenda
  - update return type from `Promise<any>` to `Promise<Context>`
  - a separate issue should be raised to add support to the appD (and perhaps also to `findIntent`) to express what context types an app should return
- happy to extend discussion group to another 4 meetings

## Action Items
- [x] @agitana Assign @pbaize to handle #362 
- [x] @kriswest Remind SWG about open votes before next meeting
- PRs and Reviews
    - [x] @kriswest #361 (update PR #375) 
    - [x] @kriswest #418 (Documentation only)
    - [x] @kriswest #426 (Documentation only)
    - [ ] @kriswest #431 (Documentation only)
    - [ ] @kriswest #432 (Create PR for final proposal @thorsent posted)
    - [x] @kriswest #434 (Documentation only, Add spec recommendation to rapid fire multiple contexts, and desktop agent should not auto-rapid fire - progress to PR)
    - [ ] @pbaize #362
    - [x] @mattjamieson #435 (Update methods.ts) 
- [ ] @rikoe Raise an issue for adding TS generics to FDC3 APIs
- [ ] @rikoe Split out separate issues for raiseIntent with data return type for other api extensions, and declaring return types in AppD intents
- [ ] @kriswest @rikoe Discuss experimental features (stage 1/stage 2) in terms of spec rewrites with LF team
- [x] @kriswest Next meeting agenda 
  - #433

**Comment by Julia-Ritter** [comment]
Julia // FINOS

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by agitana** [comment]
Aitana Myohl / FINOS

**Comment by rikoe** [comment]
Here

**Comment by kriswest** [comment]
Kris West / Cosaic

**Comment by thorsent** [comment]
Present

**Comment by Julia-Ritter** [comment]
Untracked attendees:

- Pierre Baize
