### ISSUE TITLE
Channels, Feeds & Transactions Discussion group meeting 30th Sept 2021

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#465]
## Group overview
There are currently 13 open issues in the FDC3 repository, under consideration for the 2.0 release, that relate to the existing concept of channels (both the 'system channels' used via the desktop agent API, and 'app channels' interacted with through the Channels API) and new concepts we've discussed introducing: transactions (a standardized way to make a request and receive a response back) and feeds (a standardized way to request a stream of data, such as a pricing stream).

### Relevant issue tags
Current open issues that relate to the above concepts with the label: 
[![](https://user-images.githubusercontent.com/1701764/120999635-422ebd00-c781-11eb-8033-7f6ff251605b.png)](https://github.com/finos/FDC3/labels/channels%20feeds%20%26%20transactions)

## Meeting Date
Thursday 30th Sept 2021 - 9am EDT / 2pm BST

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma12186819d04d8bce901a42f60212329)
- Meeting number: 2700 235 4634
- Password: 4eZpzMTm7J6

*More ways to join*
- Join by video system:
   - Dial 27002354634@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number.
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 270 023 54634

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC 2.0 as a whole.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #452 
  - New reviews needed:
    - #361 
      - #375
    - #418 
      - #454 
    - #426 
      - #461
    - #434 
      - #464 
    - #435
      - #462 
- [x] #433 (35mins)
- [x] Getting started on #450 (10mins)
- [x] Next meeting agenda, AOB & Adjourn (5mins)

## Minutes
#433 
- Wherever possible we should reuse existing concepts
  - However, channels currently fall short
    - E.g. Not possible to do discovery, track subscriptions, know who you are exchanging messages with etc. 
  - Identity 
    - You'll definitely want controls over who can join, or who you are listening to when working with concepts like pricing
      - with channels, any app could spoof messages, or two apps could try and push pricing streams to the same channel
    - Should credential be a concept in FDC3?
      - The spec might not define the standard for credentials, but at least allow them to be passed in some way so another app could verify them
  - Concerns raised over discovery (and firms reporting over what else was running on the desktop)
    - To a certain extent this is already possible with `findIntent`...
  - Concerns raise over 1:1 comms or authentication/authorisation for comms being against the 'spirit' of FDC3
    - we're really talking about either 1:* comms or 1:1 - the main point that on one end there is guaranteed to be a single entity (feed owner) 
    - we already doing 1:1 comms with intents - FDC3 enables it without prior coordination
    - channels are *:* comms
    - FDC3 comms is, at the moment, anonymous, does this proposal change that?
      - Not necessarily - we guaranteeing that one end of the communication is always the same entity
      - It's previously been commented that implementations of Desktop Agents could differentiate themselves with features such as security (in this case authentication) - the standard doesn't have to define how this is implemented, it only has to do the minimum necessary to enable it.  
- Resolved to allow time for proposals to be considered further and revised at the next meeting

#450 
- A quick overview was given of the following:
  - the previous attempt at dealing with app instances (#287)
    - some find this proposal counterintuitive
  - straw-man proposals that introduce less new concepts than the previous attempt (and are compatible with favoured proposal to solve #432) 
    - [Proposal A](https://github.com/finos/FDC3/issues/450#issuecomment-913777910)
    - [Proposal B](https://github.com/finos/FDC3/issues/450#issuecomment-913784782)
    - [Supplementary proposal](https://github.com/finos/FDC3/issues/450#issuecomment-913786158)
- Some positive opinions of [Proposal A](https://github.com/finos/FDC3/issues/450#issuecomment-913777910) were expressed 
  - We should arrange things so that apps don't have to create their own AppMetadata/AppInstance objects, they should always be able to use one returned to them by another API call (allows for some diversity in implementations)
- Resolved to allow time for proposals to be considered further and revised at the next meeting
    
## Action Items
- **All** Before next meeting, please review straw-man proposals already posted: 
  - [Feeds proposal](https://github.com/finos/FDC3/issues/433#issuecomment-931250290)
  - [Instances Proposal A](https://github.com/finos/FDC3/issues/450#issuecomment-913777910)
  - [Instances Proposal B](https://github.com/finos/FDC3/issues/450#issuecomment-913784782)
  - [Instances Supplementary Proposal](https://github.com/finos/FDC3/issues/450#issuecomment-913786158)
- [x] @kriswest Next meeting agenda:
  - Continue the discussion on:
    - #433
    - #450
- Rolled over from previous meetings:
  - [ ] @rikoe Raise an issue for adding TS generics to FDC3 APIs
  - [ ] @rikoe Split out separate issues for raiseIntent with data return type for other API extensions, and declaring return types in AppD intents
  - [ ] (needs PR author) #430 
  - [ ] @kriswest #431 (Documentation only)
  - [ ] @kriswest / @thorsent #432 (Create PR for final proposal @thorsent posted)
  - [ ] (needs PR author) #451
  - [ ] @pbaize #362
  - [ ] @kriswest @rikoe Discuss experimental features (stage 1/stage 2) in terms of spec rewrites with LF team

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by kriswest** [comment]
🚀

**Comment by Julia-Ritter** [comment]
Julia // FINOS

**Comment by openfin-gavin** [comment]
here

**Comment by agitana** [comment]
Aitana Myohl / FINOS

**Comment by thorsent** [comment]
Present

**Comment by pbaize** [comment]
Here

**Comment by jgavronsky** [comment]
Jane Gavronsky @ FINOS here
