### ISSUE TITLE
Channels, Feeds & Transactions Discussion group 4th Nov 2021

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#489]
## Group overview
There are currently 9 open issues in the FDC3 repository, under consideration for the 2.0 release, that relate to the existing concept of channels (both the 'system channels' used via the desktop agent API, and 'app channels' interacted with through the Channels API) and new concepts we've discussed introducing: transactions (a standardized way to make a request and receive a response back) and feeds (a standardized way to request a stream of data, such as a pricing stream).

### Relevant issue tags
Current open issues that relate to the above concepts with the label: 
[![](https://user-images.githubusercontent.com/1701764/120999635-422ebd00-c781-11eb-8033-7f6ff251605b.png)](https://github.com/finos/FDC3/labels/channels%20feeds%20%26%20transactions)

## Meeting Date
Thursday 04 Nov 2021 - 9am EDT / 1pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma12186819d04d8bce901a42f60212329)
Meeting number: 2700 235 4634
Password: 4eZpzMTm7J6

*More ways to join*
- Join by video system:
   - Dial 27002354634@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 270 023 54634

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC 2.0 as a whole.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - @kriswest #430 
    - #479
  - @kriswest #451
    - #492
- [x] #433 (30mins)
  - @ggeorgievx Provide an overview of plexus subscriptions
  - @kriswest & @thorsent: a API proposals
  - @pbaize: an example using existing concepts
- [ ] #450 (15mins)
  - How to specify instance identity in implementation-specific way
    - Returning data on running instances
    - Specifying a target instance  
- [x] Arrange any future meetings - none are currently booked (5mins)
  - Nov 18th meeting clashed with SWG
  - Nov 25th is Thanksgiving in the US
  - Dec 2nd Context Data & Intents Discussion Group kicks off
- Adjourn

## Minutes
- #433
  - Overview of how streams in Plexus work provided by @ggeorgievx 
    - which: 
      - fulfil the requirements listed in this issue
      - are based on the rxjs Observable pattern
  - Overview of two proposals posted on the issue provided by @kriswest 
    - The [first proposal](https://github.com/finos/FDC3/issues/433#issuecomment-931250290) is similar to the approach in Plexus
      - New functions were added to register a feed, discover feeds and request a feed with a specific context
    - The [second proposal](https://github.com/finos/FDC3/issues/433#issuecomment-960646989) is more similar to/re-uses existing FDC3 concepts, by using intents to handle discovery and retrieval of a 'private channel'
      - no need to split `getData` and `getChannel`, could just be getResponse and rely on a type check to determine if the response is data or a channel - you can only provide one of the other
        - this is a fairly minor implementation detail
        - is the type check more complex than having the additional function?
  - A very brief look at an [alternative proposal for implementing via existing APIs only](https://github.com/finos/FDC3/issues/433#issuecomment-960884654) was provided by @pbaize
    - a fair portion of the functionality provided by the [second proposal](https://github.com/finos/FDC3/issues/433#issuecomment-960646989) can be implemented via this route
       - with the notable exception of receiving notice that the other party has left/disconnected.
  - four meeting participants expressed a preference for the [second proposal](https://github.com/finos/FDC3/issues/433#issuecomment-960646989) 
      - all 4 commented that they liked the fact that it reuses existing concepts
      - one other meeting participant commented that they thought that this overloaded the concept of intents and that soon everything would look like an intent
        - another participant disagreed with this statement - intents are often described as verbs and are used to express an action you want another app to take - that is still how they are being used in these proposals
      - further development of the proposal is needed to allow a resolver to consider the desired response type
        - It was observed that appD has a role to play in declaring types for use by a resolver
        - e.g. additional optional args to raiseIntent & findIntent + suggest additions to appD `intents` metadata
  - Consensus was achieved that further work on the [second proposal](https://github.com/finos/FDC3/issues/433#issuecomment-960646989) should be done, to allow a resolver to consider the desired response type
-  #450
    - Due to time constraints this issue was not discussed
- Arrange any future meetings - none are currently booked 
    - There was consensus that there is indeed more to discuss and future meetings should be arranged
  
## Action Items
- [x] @kriswest Start email and slack threads on when to meet next (Ideally keep to Thursdays, e.g. 18th Nov before SWG, or 9th December)
- [ ] @kriswest @thorsent further develop the [second proposal](https://github.com/finos/FDC3/issues/433#issuecomment-960646989) for #433 to address comments above. Consider moving to a PR.
- [x] @kriswest Next meeting agenda:
  - #450 (15mins)
    - How to specify instance identity in an implementation-specific way
      - Returning data on running instances
      - Specifying a target instance  
  - #433 Review revisions to [second proposal](https://github.com/finos/FDC3/issues/433#issuecomment-960646989)
  - Using Typescript Generics to improve the FDC3 API
    - Issue to be raised (@rikoe)
    - see [this comment thread](https://github.com/finos/FDC3/issues/432#issuecomment-960651200) for some discussion
- Rolled over from previous meetings:
  - [ ] @rikoe Raise an issue for adding TS generics to FDC3 APIs
  - [x] @rikoe Split out separate issues for raiseIntent with data return type for other API extensions, and declaring return types in AppD intents
  - [ ] @kriswest #431 (Documentation only)
  - [x] @kriswest / @thorsent #432 (Create PR for final proposal @thorsent posted)
  - [ ] @pbaize #362
  - [ ] @kriswest @rikoe Discuss experimental features (stage 1/stage 2) in terms of spec rewrites with LF team

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by kriswest** [comment]
🤖 Kris // Cosaic

**Comment by agitana** [comment]
Aitana Myohl / FINOS

**Comment by bertrand-s** [comment]
Bertrand / Symphony

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by hampshan** [comment]
Andrew Hampshire

**Comment by lspiro-Tick42** [comment]
Leslie / Glue42

**Comment by pbaize** [comment]
Pierre Baize / OpenFin

**Comment by jgavronsky** [comment]
Jane Gavronsky / FINOS

**Comment by kriswest** [comment]
Poll for next meeting slot (respond by clicking on the relevant emoji):
- :one: Tuesday 16th November 9am EST, 2pm GMT
- :two: Wednesday 16th November 9am EST, 2pm GMT
- :three: Thursday 18th November 9am EST, 2pm GMT (note this is right before the Standards Working Group meeting)
- :four: Thursday 9th December 9am EST, 2pm GMT

**Comment by kriswest** [comment]
Poll for next meeting slot (respond by clicking on the relevant emoji):
- 🎉 Tuesday 16th November 9am EST, 2pm GMT
- 🚀 Wednesday 16th November 9am EST, 2pm GMT
- ❤️ Thursday 18th November 9am EST, 2pm GMT (note this is right before the Standards Working Group meeting)
- 👀 Thursday 9th December 9am EST, 2pm GMT

**Comment by kriswest** [comment]
Ok, for our next meeting we'll go for: 🎉 Tuesday 16th November 9am EST, 2pm GMT

**Comment by agitana** [comment]
> Ok, for our next meeting we'll go for: 🎉 Tuesday 16th November 9am EST, 2pm GMT

See the meeting details in the [FINOS Community Calendar](https://calendar.google.com/calendar/u/0/r/week/2021/11/16?eid=NGNrMTYxampzZDcxNXQ4dDd1cHJmZzZwYWkgZmlub3Mub3JnX2ZhYzhtbzFyZmM2ZWhzY2cwZDgwZmk4amlnQGc&ctz=America/New_York&sf=true) and copied and pasted below:

## FDC3 Channels, Feeds & Transactions Discussion group 
### Tuesday, November 16th, 9am ET / 2pm GMT
Meeting details
https://finos.webex.com/finos/j.php?MTID=m9986d7845cbfbb84a90ab072d4544dc7
Meeting number: 2558 477 5439
Password: NhUsuwmR373

Join by video system
Dial 25584775439@finos.webex.com
You can also dial 173.243.2.68 and enter your meeting number.

Join by phone
+1-415-655-0003 US Toll
+44-20319-88141 UK Toll
Access code: 255 847 75439

**Comment by Julia-Ritter** [comment]
Untracked attendees:
 - Dimiter Georgiev / Symphony
 -  yacine zalouani / UBS 
- Qiana Chen / Citi
