### ISSUE TITLE
Channels, Feeds & Transactions Discussion group 16th Nov 2021

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#504]
## Group overview
There are currently 10 open issues in the FDC3 repository , under consideration for the  [2.0 release](https://github.com/finos/FDC3/milestone/5), that relate to the existing concept of channels (both the 'system channels' used via the desktop agent API, and 'app channels' interacted with through the Channels API) and new concepts we've discussed introducing: transactions (a standardized way to make a request and receive a response back) and feeds (a standardized way to request a stream of data, such as a pricing stream).

### Relevant issue tags
Current open issues that relate to the above concepts with the label: 
[![](https://user-images.githubusercontent.com/1701764/120999635-422ebd00-c781-11eb-8033-7f6ff251605b.png)](https://github.com/finos/FDC3/labels/channels%20feeds%20%26%20transactions)

## Meeting Date
Thursday 16 Nov 2021 - 9am EST / 2pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=m9986d7845cbfbb84a90ab072d4544dc7)
Meeting number: 2558 477 5439
Password: NhUsuwmR373

*More ways to join*
- Join by video system:
   - Dial 25584775439@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 255 847 75439

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC 2.0 as a whole.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting and other activity (10mins)
  - #489 
  - #430 
    - #479 
  - #432 
    - #495 
      - See @nkolba's comments on the PR #495  
  - #498
    - #499 
  - #451 
    - #492
  - #308
    - #496 
- [x] #450 (15mins)
  - Work on how to specify instance identity in an implementation-specific way
    - Returning data on running instances
    - Specifying a target instance
- [ ] Using Typescript Generics to improve the FDC3 API (15mins)
  - Issue to be raised (@rikoe)
  - see [this comment thread](https://github.com/finos/FDC3/issues/432#issuecomment-960651200) for some discussion
- [ ] #433 
  - Review revisions to [second proposal](https://github.com/finos/FDC3/issues/433#issuecomment-960646989) (10 mins)
- [x] AOB & Adjourn (5mins)

## Minutes
- #450 
  - Consensus was achieved that future work should focus on proposal A
    - Meeting participants contributed that: 
      - Users of the standard should be encouraged to pass metadata objects, returned to them by other API calls, in order to define targets (which allows for some variation of the metadata content between implementations).
      - Rather than introduce a new interface (that extends AppMetadata) to represent an instance of app, we could use an optional field on AppMetadata, that if set, indicates that the object represents an existing instance of an App. Introducing a new type may complicate the signature of API functions.
      - A Desktop agent may want or need to pass more information about an instance than just an id
        - For example, data might be passed to help identify the instance on the screen or provide a friendly name for the instance (in addition to a technical identifier for the instance).
      - There were obvious use-cases for interacting with an instance that you've previously interacted with, e.g. because you opened it (`fdc3.open` or `fdc3.raiseIntent`) - but they were unclear on use-cases for finding an existing instance. Such use-cases need to be re-articulated.
        - Other participants mentioned creating your own intent resolver within an app (the use-case for `findIntent`) or re-using an existing instance that a user launched manually or was otherwise already in the workspace, which they didn't want to duplicate with an additional instance (e.g. a price chart for general use).
        - Changes to `raiseIntent`/`IntentResolution` need to be addressed by the proposal
      - A two-step process, where functions like `findIntent` return only a single `AppMetadata`, with instances being returned by a `findInstance` API call are undesirable.
    - This discussion was particularly challenging to follow and future discussions should be centred on a proposal and proposed revisions to it to ensure that the discussion is easier to follow
      - Participants are encouraged to bring concrete proposals or counter-proposals to future meetings
- Next meeting: Tuesday 30th Nov 9am GMT / 2pm EST

  

## Action Items
- [x] @kriswest Attempt to update proposal A based on today's discussion of #530
- [x] @Julia-Ritter Book next meeting slot / webex: Tuesday 30th Nov 9am GMT / 2pm EST
- [x] @kriswest Next meeting agenda:
  - Using Typescript Generics to improve the FDC3 API (20 mins)
    - Issue to be raised (@rikoe)
    - see [this comment thread](https://github.com/finos/FDC3/issues/432#issuecomment-960651200) for some discussion
  - #433 (15 mins)
    - Review revisions to [second proposal](https://github.com/finos/FDC3/issues/433#issuecomment-960646989)
  - #450 (15 mins)
    - Review updated or new proposals
- Rolled over from previous meetings:
  - [ ] @rikoe Raise an issue for adding TS generics to FDC3 APIs
    - see [this comment thread](https://github.com/finos/FDC3/issues/432#issuecomment-960651200) for some discussion
  - [x] @kriswest #431 (Documentation only)
  - [x] @pbaize #362
  - [x] @kriswest @rikoe Discuss experimental features (stage 1/stage 2) in terms of spec rewrites with LF team
  - [x] @kriswest @thorsent further develop the [second proposal](https://github.com/finos/FDC3/issues/433#issuecomment-960646989) for #433 to address comments from meeting #489. Consider moving to a PR.

    
## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by kriswest** [comment]
🚀 Kris West / Cosaic

**Comment by MichaelMCoates** [comment]
Michael Coates / OpenFin

**Comment by bertrand-s** [comment]
Bertrand / Symphony

**Comment by hampshan** [comment]
Joined

**Comment by openfin-gavin** [comment]
Gavin Lauchlan / OpenFin

**Comment by pgn-vole** [comment]
Yacine Zalouani / UBS

**Comment by lspiro-Tick42** [comment]
Leslie Spiro / Glue42

**Comment by rikoe** [comment]
Riko / Adaptive

**Comment by pbaize** [comment]
Pierre / OpenFin

**Comment by kriswest** [comment]
I've posted what minutes I could. Please let me know (in comments) about any omissions or errors
