### ISSUE TITLE
Context Data & Intents Discussion Group, 13 Jan 2022

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#538]
## Group overview
Summary of the purpose and scope of the group

### Relevant issue tags
If tags have been applied to relevant issues, provide details here.

## Meeting Date
Thursday 13 Jan 2022 - 10am EST / 3pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system:
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC 2.0 as a whole.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from #490 (5mins)
- [x] Brainstorm ideas for intents and context data workflows (20 mins)
       - Basic data type building blocks (date, currency, country code, etc.)
       - Orders and trade linkage
       - ViewOrganization intent
       - ...
- [x] Review PR #541 for recommendation to SWG  (5 mins)
- [ ] Review PR #443  (5 mins)
- [x] Arrange next meeting date/agenda & Adjourn (5mins)

## Minutes
- The group brainstormed ideas for intent and context data workflows:
   - Basic data type building blocks (date, currency, country code, etc.) - field types/vs. full context types
   - Orders and trade linkage, e.g. EMS child orders or parent orders, or the street orders that make up an instruction from the client
   - Order/price request/RFQ - generating tickets, generate prices - very nice to have RFQ standardised
   - `ViewOrganization` intent - is it an omission from current intents? E.g. seeing the issuer for a product. Or would you simply use an Organization context with another more specific intent, e.g. `ViewNews`?
   - Formatted text for messages or notifications, structured content - sending payload?
   - Text searches / search queries, intents for search? search results with actions?
   - Use of existing intents but with generic text - e.g. `ViewNews` for a text search string
   - Improve documentation about usage of intents so intention becomes clearer
   - Data series for blotters/charts
   - How to represent singular/multiple e.g. Instrument vs. InstrumentList 
   - Intents for issuing calculations / execute trade requests, etc. (also e.g. receiving details on trades via Symphony)
   - Show trade ticket / show order ticket with different modes
   - Show IOI, quotes - show vs. create vs. amend vs. cancel vs. clone
   - Standardise form / conventions for intents, currently only have "view" - what others should there be
- The group agreed to propose #541 to the Standard Working Group for addition the FDC3 Standard
- At the next meeting we will discuss data series for blotters/charts, which will also include #443 
- The next meeting will be in two weeks' time (Note: as there is a Standard Working Group meeting on the same day, the next meeting will be pushed to the following week, i.e. Thursday 3 February)

## Action Items
- [x] Schedule the next meeting(s) [@Julia-Ritter]
- [ ] Add `ViewHoldings` intent PR to the agenda for the next SWG meeting [@kriswest]
- [x] Kick off an email thread / discussion group for further brainstorming of intents and context data ideas [@rikoe]

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by lspiro-Tick42** [comment]
Leslie Spiro / Glue42

**Comment by kriswest** [comment]
Kris West / Cosaic

**Comment by dpraul** [comment]
Dylan / FinTech Studios

FYI the meeting link on this issue is for the wrong group - the correct link is https://finos.webex.com/finos/j.php?MTID=m18c56ed6a487a00a83f87eba7959f56d

**Comment by sarahstone-cosaic** [comment]
Sarah Stone / Cosaic

**Comment by greyseer256** [comment]
Hugh Troeger / FactSet

**Comment by nemery-flextrade** [comment]
Nathan Emery / FlexTrade

**Comment by rich-fts** [comment]
Rich Taylor / FinTech studios

**Comment by lspiro-Tick42** [comment]
Reena Raichura / Glue42
(OBO)

**Comment by dominicgifford** [comment]
Dom Gifford / IHSM

**Comment by donbasuno** [comment]
Johan - FactSet - joined a bit late :)

**Comment by symphony-adnane** [comment]
Adnane / Symphony

**Comment by Julia-Ritter** [comment]
Untracked Attendees:

- William Shotton / RBC
- Yacine / UBS 
- Andrew Hampshire / UBS

**Comment by rikoe** [comment]
Riko / Adaptive
