### ISSUE TITLE
Standard WG Meeting - February 24, 2022

### ISSUE THREAD

**Issue by Julia-Ritter** [finos/FDC3#597]
## Date
Thursday 24 FEB 2022 - 10am EST / 3pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system:
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #568
    - #581 
      - PR: #601
- [x] Proposal to appoint Editor: Hugh Troeger (Factset) @greyseer256 (10mins)
- [x] Proposal from Context Data & Intents: #497 (5mins)
  - PR: #541
- [x] FDC3 Conformance testing project introduction @nicopreto (5mins)
- [x] Voting on the future of the AppDirectory as part of FDC3 (5mins)
  - #551 
- [x] Proposal: Require propagation of originating application identity on context/intent handlers (20mins)
  - Discussion: #569
  - Issue: #520
  - Also see: #603
- [x] AOB & Adjourn (5mins)
  - Upcoming meetings
    - **Context Data & Intents**: Thursday 3rd March 2pm GMT / 9am ET
    - **Desktop Agent Bridging**: _TBC 28th Feb - 11th Mar see Poll: https://github.com/finos/FDC3/issues/585#issuecomment-1047044670_
    - **AppDirectory**: _TBC 7th - 11th March_
    - **Context Data & Intents**: Thursday 17th March 1pm GMT / 9am ET **note daylight savings time**
    - **Desktop Agent Bridging**: _TBC 14th - 25th Mar_ https://github.com/finos/FDC3/issues/585#issuecomment-1047044670
    - **Standards Working Group**: Thursday 24th March  2pm GMT / 10 am ET **note daylight savings time**
    - **AppDirectory**: _TBC 21st - 25th March_

## Minutes
- **Review action items from previous meeting**
  - All action items from Jan 27 SWG completed except last PR review for CFT discussion group PRs
- **Proposal to appoint Editor: Hugh Troeger (@greyseer256)** 
  - @kriswest highlighted the participant/editor/maintainer roles described in the README and briefly described the editor role
  - @donbasuno proposed Hugh Troeger, a software engineer at FactSet, as Editor
  - @greyseer256 briefly introduced himself
  - @kriswest described his interactions to date with HT on recent PRs
  - @greyseer256 appointment as Editor was approved by silent consensus
- **Proposal from Content Data & Intents discussion group: #541**
  - @kriswest explained that this is the first of several planned propsals from the group and directs the SWG to the relevant issues in GitHub
  - @kriswest briefly outlined the ViewHoldings intent
  - @lspiro-Tick42 commented that listing intents as part of the FDC3 standard may not be productive, but did not have an objection to this intent specifically. @kriswest advised @lspiro-Tick42 to raise as a comment to the discussion group. @lspiro-Tick42 agreed to raise with the discussion group.
  - #541 was approved by silent consensus
- **FDC3 Conformance Testing Project**
  - @nicopreto outlined that ScottLogic are starting a project to provide a framework to confirm that DesktopAgent implementations provide complete and conformant implementations of the FDC3 standard
  - @ColinEberhardt highlighted that their intention is to work in the open and contributed it via PR into the FDC3 project
  - @lspiro-Tick42 suggested that CE/NP may want to use the Glue42 open source FDC3 implementation for testing
  - @nicopreto requested help from anyone who may be interested
  - @kriswest highlighted that the project will target FDC3 1.2 at present and move on to 2.0 as the specification becomes clearer
- **Voting on the future of the AppDirectory as part of FDC3: #551**
  - @kriswest: There have been a number of opportunities for participants to provide their opinions on issue #551, which seeks to remove the App Directory from the FDC3 standard, both through the Standards Working Group meetings and the AppD discussion group recently set-up.
    These discussions have not been wholly productive and it is the consensus of the FDC3 maintainers that we should move to a vote on the issue, in order to gauge the consensus of the community on the issue and to allow us to move on.
    We propose to open the vote to enrolled "participants" in FDC3, who can cast their votes by sending an email to [fdc3-participants@finos.org](mailto:fdc3-participants@finos.org).
    This is the same procedure used to vote on adoption of Standard versions and will be used to approve the final pre-draft of FDC3 2.0
  - If you have not yet enrolled as a voting participant you can do so by visiting the FDC3 readme on Github and clicking on the link in the [enrollment section of the FDC3 README](https://github.com/finos/FDC3/#fdc3-participants).
  - If you have any doubts about whether you are able to enroll as a voting participant please contact the FDC3 maintainers on [fdc3-maintainers@finos.org](mailto:fdc3-maintainers@finos.org) or FINOS directly who can help you work that out.
   - We intend to allow some time for active participants that have not yet enrolled to do so. Hence, we'll announce dates and procedures for the vote via email (and on the relevant issue) in due course.
  - @kriswest confirmed that there can be multiple members per organisation and that decisions are made on the basis of consensus of the participants.
  - For more details on decision making in FDC3 see the [Governance document](https://github.com/finos/FDC3/blob/master/GOVERNANCE.md#2decision-making)

- **Proposal: Require propagation of originating application identity on context/intent handlers #520**
  - @bertrand-s gave high level description of the proposal
  - @dimiter-georgiev explained that without this any intent being raised to send a message via Symphony would require a pop-up asking for user confirmation
  - @kriswest signposted the SWG to the discussion in GitHub and asked for comments to go there: #569
  - A meeting participant asked whether this information could be spoofed
  - @kriswest described how the proposed implementation may help prevent spoofing (by requiring a Desktop Agent implementation to supply the information to a context or intent listener)
  - @OpenFin-johans asked if there is a specific discussion group for this proposal
    - @kriswest Not currently, I suggest we work on the discussion for now and then if the issue can't be decided at our next meeting, split of a discussion group to work on a proposal
  - @MichaelMCoates commented that on first glance he thought it shouldn't be a "MUST" implement for the standard and would comment on the GitHub discussion
  - Some discussion ensued covering the advantages/disadvantages of the proposal, whether it would be mandatory or optional and some options for technical implementation
  - @kriswest confirmed that this would be added to the agenda for the next SWG and offered to summarize some of the points made and possible ways forward on the discussion #569 
- **AOB**
  - There were no additional items raised

### Decisions Made
- Hugh Troeger (@greyseer256) to be appointed as an Editor of the FDC3 Standard
- ViewHoldings intent PR to be merged: #541
- Issue #520 to be handled through discussion #569 until next meeting, where we will attempt to decide it OR split off a discussion group to work on a proposal.

## Action Items
- [x] @Julia-Ritter or @agitana Add Hugh Troeger to fdc3-editors team and fdc3-maintainers slack channel
- [x] @kriswest ViewHoldings intent PR to be merged: #541
- [x] @lspiro-Tick42 To raise concerns about standardizing intents with the Context Data & Intents discussion group
- [x] @kriswest Set up vote on #551, email mailing lists(s) with instructions and comment on the issue with the same
  - [x] Arrange AppD discussion group meetings to start again after vote
- [x] @kriswest Add notes on #520 to #569
- [x] @kriswest Add to next meeting agenda
  - Further discussion of #520

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by ColinEberhardt** [comment]
Colin E (Scott Logic)

**Comment by mattjamieson** [comment]
:wave:

**Comment by tpina** [comment]
Tiago Pina / Cosaic

**Comment by kriswest** [comment]
Kris West / Cosaic

**Comment by dschleifer** [comment]
Dan Schleifer (Cosaic)

**Comment by pauldyson** [comment]
Paul Dyson (Singletrack)

**Comment by greyseer256** [comment]
Hugh Troeger / FactSet

**Comment by nicopreto** [comment]
Nico Pretorius (Scott Logic)

**Comment by openfin-johans** [comment]
Johan / OpenFin 🎁

**Comment by lspiro-Tick42** [comment]
Leslie - Glue42

**Comment by jgavronsky** [comment]
Jane @ FINOS here

**Comment by WatsonCIQ** [comment]
Chris Watson / Cosaic

**Comment by Qiana-Citi** [comment]
Qiana / Citi

**Comment by bertrand-s** [comment]
Bertrand / Symphony

**Comment by openfin-gavin** [comment]
Gavin Lauchlan | OpenFin

**Comment by AidanZealley** [comment]
Aidan Zealley / Scott Logic

**Comment by timjenkel** [comment]
Tim Jenkel / Wellington

**Comment by pierreneu** [comment]
Pierre Neu / Symphony

**Comment by sarahstone-cosaic** [comment]
Sarah Stone / Cosaic

**Comment by agitana** [comment]
Aitana Myohl / FINOS

**Comment by dimiter-georgiev** [comment]
Dimiter Georgiev / Symphony

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by MichaelMCoates** [comment]
Michael Coates / OpenFin
