### ISSUE TITLE
Context Data & Intents Discussion group - 3rd March 2022

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#612]
# Group overview
At the FDC3 Use Cases Roundtable London, October 5th 2021 participants agreed that the FDC3 lexicon needs to be expanded, both with additional intents and context types to support Use Cases, but also to include more primitive data types in order to construct complex types. A number of participants also agreed that now is an appropriate time to expand the Lexicon.

See #455 for full details of the meeting outcomes.

This group is being convened to discuss and arrange work to contribute further Context types and Intents to support Use Cases being implemented by participants.

### Relevant issue tags
Current open issues that relate to the discussion group: 
[![image](https://user-images.githubusercontent.com/1701764/139841356-416d9276-81f5-4fce-b5d8-f856d4bda855.png)](https://github.com/finos/FDC3/labels/Context%20Data%20%26%20Intents)

Issues will also be tagged with the labels:
[![image](https://user-images.githubusercontent.com/1701764/139841631-c6bf8697-fafe-4266-8552-63a648625e8b.png)](https://github.com/finos/FDC3/labels/context-data)
[![image](https://user-images.githubusercontent.com/1701764/139841690-969a9d14-a0aa-44a7-bdfe-8c4a43ad30d9.png)](https://github.com/finos/FDC3/labels/intents)

## Meeting Date
Thursday 03 March 2022 - 9am EST / 2pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=m57c360c6c75eabef623127be2973d856)
Meeting number: 2555 803 6153
Password: 5mqDb2CM2ZF)

*More ways to join*
- Join by video system:
   - Dial 25564955451@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2555 803 6153

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC 2.0 as a whole.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #596  
- [x] Discuss/reaffirm why we are proposing standardized intents (5mins)
- Discuss new issues (35mins):
  - [x] #589 
  - [x] #590 
  - [x] #591 
  - [ ] #592 
- [x] Review any updates or examples added to (10mins)
  - #574 
  - #575
  - #443 
- [x] AOB & Adjourn (5mins)

## Minutes
- Discuss/reaffirm why we are proposing standardized intents
  - Why is it helpful to add the intent names to the standard?
    - Groups the same action from multiple apps under same intent for `findIntent`/`raiseIntent`
    - Can program directly to the named intent (add a ViewChart button etc.)
    - If we don't standardize names we promote fragmentation (viewChat, viewCharting, visualize etc.)
  - Its not a good use of time for working group to consider lots of individual proposals for intent names (as we did for ViewHoldings)
    - Decision: Aim to raise a single batch of considered issues and associated PRs for inclusion in FDC3 2.0 (including any breaking changes)
- #589 
  - When working with a client it's helpful to be able to view your interactions with the client or firm
    - E.g. Research is a primary interaction that is tracked by firms against individuals and clients,
  - Some further discussion of naming or purpose (should it be plural, or include 'history')
    - Might include upcoming interactions - so not just history (to be clarified in the description)
    - Use case is always multiple interactions, NOT retrieving a single interaction
    - Decision: rename ViewInteractions
  - Future discussion: naming conventions for intents that retrieve data vs. those that trigger a UI (e.g. GetInteractions vs. ViewInteractions)
  - Approved by group, @pauldyson to raise PR
- #590 
  - Clarify that CRM systems often start off emails (rather than Outlook) - usually retrieving something via the CRM to send to the recipient (e.g. selecting research, which then gets logged by CRM) and tracking the email
  - Likely to want to specify more about the email e.g. set title, body, template, content to attach?
    - Use case for RichText data 
    - additional fields should be optional
    - Use mailto: link spec and options as inspiration
    - Will require a context defining an email context as an alternative to Contact or ContactList (should support them all)
  - Action: Clarify description, add email context type to proposal, add `fdc3.nothing` as a context option (bring up blank email)
  - discuss again next meeting    
- #591 
  - Easy to understand
  - Action: rename CreateOrUpdateContact, add `fdc3.nothing` as a context option (bring up blank form), add detail about returning data (Contact context with updated data).
  - No objections to this moving to a PR as well
- #592 
  - Defer to next meeting
  - Define some interaction types
- #574
  - discuss next meeting
  - Updates to proposal pending
- #575
  - Briefly discussed templating messages
  - Updates to proposal pending
  - Still recommended for an @experimental flag
- Action: Start up discussion on coming up with a intent naming / standard verbs

## Action Items
- Rolled over from previous meetings:
  - [ ] @bertrand-s to raise a PR for #574 for further discussion and proposal to SWG
  - [ ] @bertrand-s to add rich text usage samples to #575 
  - [ ] @pauldyson to raise a PR for `ViewProfile` intent, deprecate `ViewContact`
  - [ ] @pauldyson to raise a PR for `ViewResearch` intent
  - [ ] @kriswest split #443 up into multiple PRs:
    - ISO dates and other primitive types
    - Chart context, settings and static data
    - Position, Trade, Valuation
    - Currency
    - DateRange -> TimeRange
- [ ] @pauldyson  #589 
  - rename ViewInteractions
  - raise PR
- [ ] @pauldyson  #590 
  - Clarify description (include CRM use case description), 
  - add an email context type to the proposal allowing specification of additional fields, 
  - add `fdc3.nothing` as a context option (bring up blank email)
- [ ] @pauldyson  #591
  - rename CreateOrUpdateContact, 
  - add `fdc3.nothing` as a context option (bring up blank form), 
  - add detail about returning data (Contact context with updated data)
  - raise PR (if you think it ready)
- [ ] @rikoe or @kriswest Agenda items for next meeting:
  - Add intent naming guidelines / standard verbs to Standard (including for intents that retrieve data vs. those that trigger a UI, e.g. GetInteractions vs. ViewInteractions)
  - Updates to #590
  - Updates to #591
  - Updates to #592
  - #574

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

[https://finos.webex.com/finos/j.php?MTID=m57c360c6c75eabef623127be2973d856](https://www.google.com/url?q=https://finos.webex.com/finos/j.php?MTID%3Dm57c360c6c75eabef623127be2973d856&sa=D&source=calendar&ust=1646581219224963&usg=AOvVaw3cymyYXnlYJShmtXJ7PxGt)
Meeting number: 2555 803 6153
Password: 5mqDb2CM2ZF

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by nemery-flextrade** [comment]
Nathan / Flex

**Comment by pauldyson** [comment]
Paul / Singletrack

**Comment by kriswest** [comment]
Kris / Cosaic

**Comment by pierreneu** [comment]
Pierre Neu / Symphony

**Comment by agitana** [comment]
Aitana Myohl / FINOS

**Comment by hampshan** [comment]
Andrew Hampshire / UBS

**Comment by lspiro-Tick42** [comment]
Leslie / Glue42

**Comment by Soul-Master** [comment]
Sumit / LSEG

**Comment by dominicgifford** [comment]
Dom / S&P Global

**Comment by greyseer256** [comment]
Hugh Troeger / FactSet

**Comment by jgavronsky** [comment]
Jane @ FINOS here

**Comment by Julia-Ritter** [comment]
Untracked attendees: 

- Sarah Stone/ Cosaic
- Nico Pretorius / Scott Logic
- Yacine Zalouani / UBS
- Dimiter Georgiev / Symphony
- Matt Jamieson /  White Dog
- Vinay Mistry / Symphony
