### ISSUE TITLE
App Directory Discussion group - Tuesday 3rd May 2022

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#688]
## Group overview
Discussion group to develop proposals for the improvement of the App Directory as part of the FDC3 standard. The group will examine the role/value/necessity of the AppD as part of the FDC3 specification and a compliance requirement for use of the FDC3 API, in addition to working on proposals to improve the description and functionality of the App Directory. 

### Relevant tags
Current open issues and PRs that relate to the above concepts with the label: 
[![image](https://user-images.githubusercontent.com/1701764/151783600-e65898db-0145-45bc-b500-2e3cf7b1010a.png)](https://github.com/finos/FDC3/labels/app-directory)

A [github discussion](https://github.com/finos/FDC3/discussions/618) is also available for this group (may be used to arrange meetings, agenda ask questions etc.)

## Meeting Date
Tuesday 03 May 2022 - 9am EDT / 2pm BST

### WebEx info
- Meeting Link: (https://finos.webex.com/finos/j.php?MTID=m2316d45da678d0203fd86f9342ff63ab) 
- Meeting number: 2551 735 2618

*More ways to join*
- Join by video system:
   - Dial 25517352618@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2551 735 2618

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC 2.0 as a whole.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (10mins)
  - #664 
  - Overview of [progress on PRs](https://github.com/finos/FDC3/pulls?q=is%3Apr+label%3Aapp-directory+)
- [x] #550 (close if no further activity or interest) (5mins)
- Discuss issues relating to 'Improving the AppD API' (30mins):
  - [x] #370
  - [x] #311
  - [x] #565
  - [x] #557
  - [x] #566
  - [ ] #559
- Discuss other issues (if time):
  - [ ] Revist proposals for #247
    - https://github.com/finos/FDC3/issues/247#issuecomment-1113287881 
  - [ ] #674
  - [ ] #312
  - [ ] #563
- Adjourn

## Minutes
- A summary of PRs resolving previously discussed issues was provided by @kriswest
  - All appD PRs can be found [here](https://github.com/finos/FDC3/pulls?q=is%3Apr+label%3Aapp-directory+)
  - A consolidated update PR is being added to as most of the PRs update the same YAML document and will often conflict:
    - #668
    - Currently incorporates PRs:
      - #570 
      - #658 
      - #666
      - #669 
      - #670
    - Open PRs due to be merged into it:
      - #671 
      - #673 
      - #675
- #550 
  - @openfin-johans requested that we bump this to next meeting and he will discuss with @openfin-gavin
    - As many of the underlying issues have now been resolved they may decide to close the issue without further discussion
- **Discuss issues relating to 'Improving the AppD API':**
  - #370
    - There was generally consensus that the current search API parameters are not what most developers/users would expect and hence standardizing this API is not helping anyone.
      - `appId` parameter is redundant with the GET retrieval method
      - there are separate search parameters for text fields: `description`, `title`, `tooltip`
      - search by the `version` or manifest URL is unlikely to be useful
      - there are 3 separate fields for searching intents - usage is poorly described
    - A proposal should be raised to update the definition of this API such that: 
      - a more conventional 'keyword' search is provided, where multiple text fields are searched including title, description, tooltip etc.
      - you can filter by category (with or without a keyword search)
      - search by intent name could/should be retained
        - however it was noted that this is severely limited by the inability to list all intents (and contexts) found in the app directory 
        - @kriswest@ we've seen a number of appD implementations add endpoints to list intents and contexts (including electron-fdc3 and the demo Citi provided)
          - An issue should be raised to add these endpoints to the standard to support filtering.
          - This also supports the use case for #247 (as contexts are regularly used through the broadcast API and intents may be raised rather than resolved, so the current config doesn't reference all intents and contexts that may be used)
  - #311
    - The main use case that this function would support is building a launcher application - which is often considered the province of the Desktop Agent itself, rather than an application
    - @nkolba App Directories support authentication and this API call would bypass that (to a certain extent) by forwarding on the information gathered under the auth that the Destkop Agent had used. This risks leaking data about the apps available in the desktop that might not otherwise be available
    - @kriswest We could consider an alternative proposal:: add an API call to retrieve the list of App Directories that are in use. 
      - That would resolve the question about authentication, but it probably also negates any utility (where auth is in use) as an app that retrieves the list of directories and queries them directly can't expect to receive the same data as the desktop agent did.
    - There was no consensus that this issue should move forward. The group resolved to take the discussion to the issue and to remove it from the 2.0 milestone until consensus is achieved. 
  - #565
    - Currently handled through the search API with no parameters by most implementations
    - PR to be raised to improve documentation and _possibly_ to introduce a dedicated call.
  - #557
    - There was general consensus that:
      - Pagination controls are somewhat anachronistic
      - "This would be a nice problem to have!" - referring to there being so many apps in an appD that pagination is needed.
      - We should close the issue and re-open it again if there are reports of issues with too large responses in future.
  - #566
    - There seem few use cases for dynamically adding to an appD at present and hence there was general consensus that standardizing this API call is unnecessary. It should be removed for the timebeing. 
  - #559
    - Not discussed due to time constraints.

## Action Items
- [x] @kriswest Create next meeting agenda around PR prep and review (to prepare consolidated PR for next SWG meeting)
  - Future meetings beyond 2.0 should consider remaining issues:
    - #559 
    - #674
    - #312
    - #563
- [x] @kriswest Add an 'other' category to categories PR and merge into consolidated PR.
- [x] @kriswest raise an issue for adding /intents and /contexts endpoints to appD API
  - #719
- [x] @kriswest raise a PR to resolve #565
  - #694
- [x] @kriswest raise a PR to resolve #566
  - #695  
- [x] @kriswest close #557

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by kriswest** [comment]
Kris West / Cosaic 🚀

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by thorsent** [comment]
Terry / Cosaic

**Comment by mistryvinay** [comment]
Vinay / Symphony

**Comment by openfin-johans** [comment]
Johan / OpenFin / First half only...

**Comment by MichaelMCoates** [comment]
Michael Coates / OpenFin

**Comment by nkolba** [comment]
Nick Kolba

**Comment by mcleo-d** [comment]
👋🏻

**Comment by Julia-Ritter** [comment]
**Untracked Attendees:**

Derek / Proton Mail
Frank Bader / Wellington
Dimiter Georgiev / Symphony
