### ISSUE TITLE
Standard WG Meeting - May 26, 2022

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#728]
## Date
Thursday 26th May 2022 - 10am EST / 3pm BST

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system:
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  -  #683
- [x] Report on formal specification project and outstanding work (5mins)
  - #484
  - #636 
- Review PRs for inclusion in FDC3 2.0 (40mins)
  - [x] #668 
    - Resolves issues:
      - #369
      - #370
      - #553
      - #555
      - #556
      - #558
      - #560
      - #561
      - #562
      - #565
      - #566
      - #567
      - #622  
    - Preview links:
      - [AppD Overview](https://deploy-preview-668--lambent-kulfi-cf51a7.netlify.app/docs/next/app-directory/overview)
      - [API introduction](https://deploy-preview-668--lambent-kulfi-cf51a7.netlify.app/docs/next/app-directory/spec)
      - [Full OpenAPI specification](https://deploy-preview-668--lambent-kulfi-cf51a7.netlify.app/schemas/next/app-directory)
  - [x] #724
    - Resolves issues:
      - #574
      - #587
      - #588 
      - #589 
      - #590 
      - #600
      - #624 
      - #645 
      - #646 
      - #651 
      - #652 
      - #654
      - #681
    - Preview links:
      - [Intents Overview](https://deploy-preview-724--lambent-kulfi-cf51a7.netlify.app/docs/next/intents/spec)
        - [Intent naming conventions](https://deploy-preview-724--lambent-kulfi-cf51a7.netlify.app/docs/next/intents/spec)
      - [Context Overview](https://deploy-preview-724--lambent-kulfi-cf51a7.netlify.app/docs/next/context/spec)
        - [Field type conventions](https://deploy-preview-724--lambent-kulfi-cf51a7.netlify.app/docs/next/context/spec#field-type-conventions)
      - New intents
        - [StartChat](https://deploy-preview-724--lambent-kulfi-cf51a7.netlify.app/docs/next/intents/ref/StartChat)
        - [ViewHoldings](https://deploy-preview-724--lambent-kulfi-cf51a7.netlify.app/docs/next/intents/ref/ViewHoldings)
        - [ViewInteractions](https://deploy-preview-724--lambent-kulfi-cf51a7.netlify.app/docs/next/intents/ref/viewinteractions)
        - [ViewOrders](https://deploy-preview-724--lambent-kulfi-cf51a7.netlify.app/docs/next/intents/ref/ViewOrders)
        - [ViewProfile](https://deploy-preview-724--lambent-kulfi-cf51a7.netlify.app/docs/next/intents/ref/ViewProfile)
        - [ViewResearch](https://deploy-preview-724--lambent-kulfi-cf51a7.netlify.app/docs/next/intents/ref/ViewResearch)
      - New contexts:
        - [Chart](https://deploy-preview-724--lambent-kulfi-cf51a7.netlify.app/docs/next/context/ref/chart)
        - [ChatInitSettings](https://deploy-preview-724--lambent-kulfi-cf51a7.netlify.app/docs/next/context/ref/chatinitsettings)
        - [Currency](https://deploy-preview-724--lambent-kulfi-cf51a7.netlify.app/docs/next/context/ref/Currency)
        - [TimeRange](https://deploy-preview-724--lambent-kulfi-cf51a7.netlify.app/docs/next/context/ref/TimeRange)
        - [Valuation](https://deploy-preview-724--lambent-kulfi-cf51a7.netlify.app/docs/next/context/ref/valuation)
  - [x] #722 
    - Preview links:
      - [New `AppIdentifier` type](https://deploy-preview-722--lambent-kulfi-cf51a7.netlify.app/docs/next/api/ref/types) used for target parameters
      - [`AppMetadata` extends `AppIdentifier`](https://deploy-preview-722--lambent-kulfi-cf51a7.netlify.app/docs/next/api/ref/metadata#appmetadata) and is used for returns
      - [`open`, `raiseIntent` & `raiseIntentForContext`](https://deploy-preview-722--lambent-kulfi-cf51a7.netlify.app/docs/next/api/ref/desktopagent#open) updated signatures
      - [Deprecated versions of `open`, `raiseIntent` & `raiseIntentForContext`](https://deploy-preview-722--lambent-kulfi-cf51a7.netlify.app/docs/next/api/ref/desktopagent#open-deprecated)
  - [x] #725 
    - Preview links:
      - New [`ContextMetadata` type](https://deploy-preview-725--lambent-kulfi-cf51a7.netlify.app/docs/next/api/ref/metadata#contextmetadata)
      - Updated [`ContextHandler` and `IntentHandler`](https://deploy-preview-725--lambent-kulfi-cf51a7.netlify.app/docs/next/api/ref/types#contexthandler) types
      - Comments about optional exposure of originating app metadata on [raised intents](https://deploy-preview-725--lambent-kulfi-cf51a7.netlify.app/docs/next/api/spec#originating-app-metadata)  and on [channels](https://deploy-preview-725--lambent-kulfi-cf51a7.netlify.app/docs/next/api/spec#originating-app-metadata-1) 
  - [x] #726 
    - Preview links:
      - [Updated `ImplementationMetadata` type](https://deploy-preview-726--lambent-kulfi-cf51a7.netlify.app/docs/next/api/ref/metadata#implementationmetadata)
      - [Updated detail in overview](https://deploy-preview-726--lambent-kulfi-cf51a7.netlify.app/docs/next/api/spec#retrieve-metadata-about-the-desktop-agent-implementation) 
  - [x] #727
    - [Preview link](https://deploy-preview-727--lambent-kulfi-cf51a7.netlify.app/docs/next/api/spec#recommended-user-channel-set)
    - [Typescript export](https://github.com/finos/FDC3/blob/085d0483efa564c49cec8ab11088c87f07fa0df4/src/api/RecommendedChannels.ts) 
  - [x] #731 
    - [Preview Link](https://deploy-preview-731--lambent-kulfi-cf51a7.netlify.app/schemas/next/app-directory#tag/Application/paths/~1v2~1apps~1{appId}/get)
- [ ] FINOS - [Open Source in Finance Forum London ](https://events.linuxfoundation.org/open-source-finance-forum-london/) 
- [x] AOB & Adjourn (5mins)

## Minutes
- #484 & #636
  - Approved to raise and merge PR prior to next meeting, with changes as described in the issues 
- #668 
  - Approved to merge (silent consensus)
- #724 
  - Approved to merge (silent consensus)
- #722 
  - Approved to merge (silent consensus)
- #725
  - @nkolba suggested a number of changes, including:
    - Upgrading from a recommended, but optional feature (SHOULD) to required (MUST)
      - @kriswest proposed that we do this and open an email vote to include the revised PR - this proposal was superseded by a later one
    - Switch from `AppMetadata` to `AppIdentifier` for reasons of developer ergonomics and to avoid variation in implementations based on what fields Desktop Agents choose to return in `AppMetadata` 
      - Requires the additional of a further API call to retrieve `AppMetadata` for an `AppIdentifier`
      - @kriswest pointed out that this is inconsistent with the rest of the API and that this could also result in variations
    - @kriswest proposed that we apply the [experimental label](https://fdc3.finos.org/docs/next/fdc3-compliance#experimental-features) to this feature (in the ContextMetadata type introduced to handle this metadata), merge it and seek to refine it in a new issue
      - @nkolba offered to raise the issue
  - Approved to merge (silent consensus) - after application of the experimental label
- #726
  - Approved to merge (silent consensus)
- #727
  - A query was raised about whether an expert on color and UIs for the colorblind had been or could be consulted on the chosen colors
    - @kriswest explained how the colors were chosen, aiming for as much contrast as possible ( although this is challenging with a set of 8) and that our primary mechanism for supporting the colorblind is the use of the glyphs included in the display metadata
  - A query was raised about using HEX colors
    - @kriswest clarified that the keywords are from CSS3 and do imply specific hex values, also that it was requested that we use keywords to allow some small variation where it is deemed necessary, with goal being that it is still recognized as the same color.
  - @kriswest demonstrated the updated channel ids, to which namespacing was added to avoid collision with existing channels, on a suggestion from @openfin-johans 
  - @lspiro-Tick42 suggested that we also consider a standard mapping to Bloomberg and Eikon channels
    - @kriswest acknowledged the value of doing so, but requested that this be raised as a separate issue
  - Approved to merge (silent consensus)
- #731
  - @kriswest provided an overview of the PR and clarified the use cases (find apps to interop with in an appD browser, document FDC3 interface to an app for developers) and that the all additional metadata (other than intents listened for) is optional 
  - The end of the meeting curtailed discussion and consensus checking.
  - @kriswest to summarize issue via email and request approval to merge

## Action Items
- [x] @finos/fdc3-maintainers & @finos/fdc3-editors to complete review tasks and merge approved PRs into FDC3 2.0 pre-draft.
- [x] @kriswest apply the experimental label to #725 prior to merging
- [x] @nkolba raise an issue to discuss refining #725 and introducing an API call to retrieve `AppMetadata` for an `AppIdentifier` 
- [ ] @lspiro-Tick42 & @ggeorgievx raise an issue to consider how the recommended channel list can be mapped to Bloomberg and Eikon channel lists
- [x] @kriswest summarize #731 and open a vote via email for inclusion in the FDC3 2.0 predraft.

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by kriswest** [comment]
Kris West / Cosaic

**Comment by mistryvinay** [comment]
Vinay / Symphony

**Comment by pauldyson** [comment]
Paul Dyson / Singletrack

**Comment by timjenkel** [comment]
Tim / Wellington

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by jgavronsky** [comment]
Jane / FINOS

**Comment by RandallDang-Citi** [comment]
Randall Dang / Citi

**Comment by ggeorgievx** [comment]
Georgi / Tick42

**Comment by lspiro-Tick42** [comment]
Leslie / Glue42

**Comment by milindchidrawar** [comment]
Milind Chidrawar / Singletrack

**Comment by sarahstone-cosaic** [comment]
Sarah Stone / Cosaic

**Comment by openfin-johans** [comment]
Johan / OpenFin

**Comment by mattjamieson** [comment]
:wave:
