### ISSUE TITLE
Context Data & Intents Discussion group - 4 Aug 2022

### ISSUE THREAD

**Issue by mistryvinay** [finos/FDC3#791]
## Group overview
At the FDC3 Use Cases Roundtable London, October 5th 2021 participants agreed that the FDC3 lexicon needs to be expanded, both with additional intents and context types to support Use Cases, but also to include more primitive data types in order to construct complex types. A number of participants also agreed that now is an appropriate time to expand the Lexicon.
​
See https://github.com/finos/FDC3/issues/455 for full details of the meeting outcomes.
​
This group is being convened to discuss and arrange work to contribute further Context types and Intents to support Use Cases being implemented by participants.

### Relevant issue tags
Current open issues that relate to the discussion group: 
[![image](https://user-images.githubusercontent.com/1701764/139841356-416d9276-81f5-4fce-b5d8-f856d4bda855.png)](https://github.com/finos/FDC3/labels/Context%20Data%20%26%20Intents)

Issues will also be tagged with the labels:
[![image](https://user-images.githubusercontent.com/1701764/139841631-c6bf8697-fafe-4266-8552-63a648625e8b.png)](https://github.com/finos/FDC3/labels/context-data)
[![image](https://user-images.githubusercontent.com/1701764/139841690-969a9d14-a0aa-44a7-bdfe-8c4a43ad30d9.png)](https://github.com/finos/FDC3/labels/intents)

## Meeting Date
Thursday 4 Aug 2020 - 9am EST / 2pm BST

### WebEx info
- Meeting Link: https://finos.webex.com/finos/j.php?MTID=mbb193ae433ce8d4366adcecd94355734
- Meeting number: 2556 257 8293

*More ways to join*
- Join by video system:
   - Dial 25562578293@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2556 257 8293

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #769  
- [x] Revisit status on open PR's (10mins)
   - #747 
   - #761 
   - #779 
- [x] Revisit proposals for standardised Contexts (15mins)
  - #644 
  - #655 
  - #656
- [x] Issues that require a PR to be raised (5mins)
  - #765 
  - #767 
  - #768 
  - #387 
  - #707 
- [x] Gather insights into business workflows that could be candidates for further extending FDC3 capabilities? (15mins)
  - What intents need to be created to use the new contexts?
- [ ] AOB & Adjourn (5mins)

## Minutes
- #747 Review and merge PR https://github.com/singletracksystems/FDC3/pull/7
  - resolve alphabetical sorting of contexts and intents and re-request review
- #761  
  - merge changes from #747 
- #779   
  - intent schema to be renamed to `action`
  - drop data element from message (from a previous conversation)
  - expand to support other types of actions, possibly notifications
  - consider a second PR to allow the action to be broadcast to a channel/user channels
     - Broadcasting on user channels (chat window could have a channel selected). So selected channels are pushed into a room
  - schema enum in intent. Make sense to just make it a string, or any of for enum of string
    -  list has to be maintained. And use proprietary list of intents
     - limited only use standard list of intents
     - typestring - comment link to where the standard intents are listed.
     - take intent out of required list. make intent element optional.
- #765  
  - input either a contact / room List
  - will not use `ChatInitSettings` but create a new context
  - remove `roomId`, create an `id` object which then has a field of `roomId`
- #768 
  - search for contexts embedded in chat messages
  - search for search tags. `tags` can be keyword searches
  - The need for other search or filter types, outside the scope of chat, was discussed
    - Difficult to create a type that could handle all possible query types...
      - Using a type solves an existing problem, the need to reset a filter (you send an empty query)
        - #301
    - As a starter
     - field for "free text".
     - field for an array of context objects
- #387   
  - ready to be turned into a PR, looking for volunteers to take this on
- #707    
  - consensus to include market field, with field identifiers in same pattern as id field
  - ready to be turned into a PR, looking for volunteers to take this on 
- [Business Workflows across FDC3]
  - @hampshan has started to request information from internal users regarding applications that are used across desktops
  - Further support needed in identifying business use-cases/workflows
 
## Action Items
- [x] @milindchidrawar update #747 and #761 and resubmit for review
- [ ] @nemery-flextrade to raise issue to include Type packages for other languages.
- [x] @Yannick-Symphony update #779 and resubmit for review
- [x] @symphony-jean-michael update #765, #768  and resubmit for review
- [x] @mistryvinay push review of #644 #655 #656 to next months meeting
- [ ] @kriswest or a volunteer, start working on proposal and examples for #387, use fdc3.action from #779
- [ ] @openfin-johans or @kriswest create a PR for #707 
 
## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by mistryvinay** [comment]
Vinay / Symphony

**Comment by pauldyson** [comment]
Paul / Singletrack

**Comment by nemery-flextrade** [comment]
Nathan / FlexTrade

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by milindchidrawar** [comment]
Milind / Singletrack

**Comment by kriswest** [comment]
Kris / Cosaic

**Comment by pierreneu** [comment]
Pierre Neu / Symphony

**Comment by symphony-jean-michael** [comment]
Jean-Michael Legait / Symphony

**Comment by Yannick-Symphony** [comment]
Yannick / Symphony

**Comment by katherinelachelin** [comment]
Katherine Lachelin / Iress

**Comment by jgavronsky** [comment]
Jane / FINOS

**Comment by alexandrelealbess** [comment]
Alexandre | Legalbot (Regtech)
