### ISSUE TITLE
Context Data & Intents Discussion group - 1 Sep 2022

### ISSUE THREAD

**Issue by mistryvinay** [finos/FDC3#809]
## Group overview
At the FDC3 Use Cases Roundtable London, October 5th 2021 participants agreed that the FDC3 lexicon needs to be expanded, both with additional intents and context types to support Use Cases, but also to include more primitive data types in order to construct complex types. A number of participants also agreed that now is an appropriate time to expand the Lexicon.
​
See https://github.com/finos/FDC3/issues/455 for full details of the meeting outcomes.
​
This group is being convened to discuss and arrange work to contribute further Context types and Intents to support Use Cases being implemented by participants.

### Relevant issue tags
Current open issues that relate to the discussion group: 
[![image](https://user-images.githubusercontent.com/1701764/139841356-416d9276-81f5-4fce-b5d8-f856d4bda855.png)](https://github.com/finos/FDC3/labels/Context%20Data%20%26%20Intents)

Issues will also be tagged with the labels:
[![image](https://user-images.githubusercontent.com/1701764/139841631-c6bf8697-fafe-4266-8552-63a648625e8b.png)](https://github.com/finos/FDC3/labels/context-data)
[![image](https://user-images.githubusercontent.com/1701764/139841690-969a9d14-a0aa-44a7-bdfe-8c4a43ad30d9.png)](https://github.com/finos/FDC3/labels/intents)

## Meeting Date
Thursday 1 Sep 2022 - 9am EST / 2pm BST

### WebEx info
- Meeting Link: https://finos.webex.com/finos/j.php?MTID=mbb193ae433ce8d4366adcecd94355734
- Meeting number: 2556 257 8293

*More ways to join*
- Join by video system:
   - Dial 25562578293@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2556 257 8293

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #791 
- [x] Revisit proposals for standardised Contexts (15mins)
  - #644 
  - #655 
  - #656
- [x] PR's that are ready to be reviewed (5mins)
  - #747 
  - #761 
  - #779 
  - #794 
  - #796 
  - #797  
- [x] Issues that require a PR to be raised (5mins)
  - #387 
  - #707 
- [x]  Insights into business workflows that could be candidates for further extending FDC3 capabilities? (15mins)
- [x] AOB & Adjourn (5mins)

## Minutes
- #747
    - @pauldyson indicated that such additional information is often not recorded, but he'll consider the need for it.
    - Additive changes could be made in a later PR
- #761 
  - Add recommendation to use this context type for all CRUD operation intents in Intent specification
  - merge updates from 2.0 release
  - Update `CHANGELOG.md` with entries for this PR
  - @kriswest to send PR into @milindchidrawar PR with revised Overview
- #779 
  - Consolidate chat PR's together (#765 #768 #779)
    - Dependencies between these PR's are making review more difficult. Use cases for all are accepted by the group so consolidation of the PR will simplify review by SWG.
  - Currently the proposal is quite specific for chat messages but the fdc3.message type proposed could be used, for example, by the `fdc3.email` type.
  - Description of `fdc3.message` needs to cover all use-cases
  - `entities` element uses string IDs, but doesn't demonstrate how they might be used in the message text and should be updated to do so. 
  - Can message container contain HTML?
    - yes, in the `text` element under the appropriate mime-type.
    - however plain text should always be provided as a fallback
      - This is not currently outlined in the docs or schema - the text['text/plain'] property could/should be *required* in the schema and described in docs if that's what is intended
  - No formal spec or example for representing markdown.  
  - @hampshan asked if there was a MIME type for markdown?
    - Yes there are two, but not individual ones for different markdown flavours. If this were to be used the Standard should recommend or require a particular flavour.
  - @kriswest: please link to any external standard/references for MIME types (both in the context type and references page)
- #794 
  - Deal with review comments and suggestions.
  - Consider expanding the description of StartChat to include more details on use-cases for starting a chat from a different application (e.g. a research app or OMS)
- #796 
    - Expand description of ViewChat to include use-case for opening the chat from another application (e.g. a research app, OMS or Risk application)
    - This PR also has a dependency on #794 
    - Otherwise looks good!
- #797 
  - Is this a general search criteria, or a specific search criteria for chat? The context specifically limits the criteria and query construction that can be used in a search...
    - Option 1: Make this more flexible to support all search purposes
        - We don't want to define a query for all use-cases at the moment, it would be too large an undertaking
    - Option 2: Refactor it to be chat specific, with a rename to `fdc3.chat.searchcriteria`
  - Further options for supporting more complex search criteria were discussed
    - E.g. use a Google type search
      - All search clauses are combined with `OR` 
      - Then ranked results are returned based on those `OR` search criteria values
      - Ranked in order of filter word occurrences
    - Empty search criteria could supported to allow reset of filters (which is a common issue in FDC3 for filters based on context broadcasts)
    - Rename `contexts` array to `criteria` to acknowledge that it may contain strings, not just contexts

## Action Items
- [x] @hampshan to reach out to @nemery-flextrade for next steps on #644 #655 #656 
- [x] @kriswest to send PR into @milindchidrawar for #761
- [x] @milindchidrawar to update #747 & #761 and resubmit for review
- [x] @yannick-symphony @symphony-jean-michael address feedback on chat PR's and resubmit for review
- [ ] @yannick-symphony @symphony-jean-michael to consolidate chat PR's

Rolled over from previous meetings
- [x] @nemery-flextrade to raise issue to include Type packages for other languages.
- [x] @kriswest or a volunteer, start working on proposal and examples for #387, use #779 
- [x] @openfin-johans or @kriswest create a PR for #707 

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by kriswest** [comment]
Kris / Cosaic

**Comment by Yannick-Symphony** [comment]
Yannick / Symphony

**Comment by symphony-jean-michael** [comment]
Jean-Michael / Symphony

**Comment by hampshan** [comment]
Andrew Hampshire / UBS

**Comment by dominicgifford** [comment]
Dom / SPGI

**Comment by pauldyson** [comment]
Paul / Singletrack

**Comment by pgn-vole** [comment]
Yacine Zalouani @ UBS

**Comment by greyseer256** [comment]
Hugh Troeger / FactSet

**Comment by Julia-Ritter** [comment]
**Untracked attendees:**

- Tim Jenkel / Wellington 
- Jim Bunting / Cosaic 
- Anant / Wellington
