### ISSUE TITLE
Context Data & Intents Discussion group - 6 Oct 2022

### ISSUE THREAD

**Issue by mistryvinay** [finos/FDC3#826]
## Group overview
At the FDC3 Use Cases Roundtable London, October 5th 2021 participants agreed that the FDC3 lexicon needs to be expanded, both with additional intents and context types to support Use Cases, but also to include more primitive data types in order to construct complex types. A number of participants also agreed that now is an appropriate time to expand the Lexicon.
​
See https://github.com/finos/FDC3/issues/455 for full details of the meeting outcomes.
​
This group is being convened to discuss and arrange work to contribute further Context types and Intents to support Use Cases being implemented by participants.

### Relevant issue tags
Current open issues that relate to the discussion group: 
[![image](https://user-images.githubusercontent.com/1701764/139841356-416d9276-81f5-4fce-b5d8-f856d4bda855.png)](https://github.com/finos/FDC3/labels/Context%20Data%20%26%20Intents)

Issues will also be tagged with the labels:
[![image](https://user-images.githubusercontent.com/1701764/139841631-c6bf8697-fafe-4266-8552-63a648625e8b.png)](https://github.com/finos/FDC3/labels/context-data)
[![image](https://user-images.githubusercontent.com/1701764/139841690-969a9d14-a0aa-44a7-bdfe-8c4a43ad30d9.png)](https://github.com/finos/FDC3/labels/intents)

## Meeting Date
Thursday 6 Oct 2022 - 9am EST / 2pm BST

### WebEx info
- Meeting Link: https://finos.webex.com/finos/j.php?MTID=mbb193ae433ce8d4366adcecd94355734
- Meeting number: 2556 257 8293

*More ways to join*
- Join by video system:
   - Dial 25562578293@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2556 257 8293

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #809 
- [x] PR's that are ready to be reviewed (5mins)
  - #819 
  - #824
- [ ] Revisit proposals for standardised Contexts (10mins)
  - #655 
  - #656
 - [x] PR's that are awaiting updates (5mins)  
  - #779 
  - #794 
- [x] Issues that require a PR to be raised (10mins)
  - #387 
    - #828 
- [x] PR's ready to merged into 2.1 Milestone release (1mins)
  - #747 
  - #761 
  - #796 
  - #797 
- [x]  Insights into business workflows that could be candidates for further extending FDC3 capabilities? (15mins)
- [x] AOB & Adjourn (5mins)

## Minutes
- #819 
    - Overview from @openfin-johans
    - The ID array is not enough to identify the instrument and has to use a market identifier too and the exchange code.
    - There could be further ways to identify by using the market including custom identifiers.
    - In addition to the ID there is a market object with additional fields (see the PR)
    - @kriswest and @greyseer256 felt this was good to go
    - Context types file that was not added but @kriswest feels this would be generated when it goes into the main.
- #644  
  - @kriswest is yet to give a review but mentioned a few typos and minor issues.
    - Schema is lacking the required properties (order does not have them and should)
    - Try the generation of the schema to ensure it works
  - `CreateOrder` and `UpdateOrder` intents to go with the `ViewOrder` intent would also be good to add.
  - Action items:
    - Asks for other vendors that may use this type to ensure there is an agreement
    - Call for feedback and comments / Reviews are also welcome
    - Will move this to the next meeting when @nemery-flextrade is back
    - Ask for a run-through in a future meeting to better understand.
- #794 
  - Action
    - A better description of how to use start chat is needed
    - Some of the comments need resolution @Yannick-Symphony is having a look
    - @kriswest will revisit the chat PRs next week
  - @dimiter-georgiev mentioned one use case - Rich Text Format defines action buttons in a message. The ability to add standard buttons from the calling application. When you click on the buttons can we include metadata about the chat and who is invoking the action.? E.g. viewInstrument intent how do we include the metadata?
    - @kriswest response: To include extra information you need to wrap a context inside another context. This can't be done with an intent (as it changes the context type sent out and might break integration with other apps). hence, there is not currently a good way to provide additional information.
    - More detailed metadata (about the intent and context sent) is what is needed -  @pierreneu to raise a PR to the working group to do this. 
      - #829 
      - See the [`ContextMetadata`](https://fdc3.finos.org/docs/api/ref/Metadata#contextmetadata) type
      - Potential solution: add an optional field for source metadata on the `ContextMetadata` type. It would require a change to a handful of API calls (`broadcast()`, `raiseIntent()`, `raiseIntentForContext()`) to add an optional argument allowing you to supply that metadata.
    - Follow up on this at a future meeting
- #828 
  - Most Desktop Containers have notification functionality and they need a standard way to handle notifications via FDC3.
  - Why is relevant to FDC3? Actionable Notifications, the action may need to be sent to a different application to the one that raised it in the first place - this might be the *most* common use-case!
  - Two ways to approach adding notification support:
    - Add an API to FDC3 for notifications
    - Add support for notifications using intents and contexts 
  -  The provided solution is modelled on the web notifications API
    - One difference between this is how it uses the actions array (see the PR #828)
    - Notifications sounds are also non-standard to the web notification API but oft requested
    - Notifications Feature detection is easily possible through `findIntent` - can the DA (or another app) accept notifications
  - The summary is that it could be done with Intents and Context without having to change FDC3 API.
  - @kriswest ran through the sections of the API and explained each section
    - Commenting that a standardized approach in FDC3 is likely to receive better uptake across the industry than a selection of proprietary APIs (i.e. the current state)
  - @openfin-johans feedback was that he agreed it was a good example of being able to extend FDC3 without having to extend the API/Desktop Agent implementation.
  - @openfin-johans asked @dimiter-georgiev for feedback as an end user
  - @dimiter-georgiev example: Clients say: We already have a notification platform, can we route your notifications (from Symphony) to that existing platform? Hence, a standard way of doing that in FDC3 would solve a problem for us. The end users may want to filter which messages want to be sent from Symphony to the platform.
  - @openfin-johans has suggested gaining more feedback from the participants who would be end users. Feels like people would prefer to move to a standard.
  - May help with those who are DA Platform agnostic 
  - @openfin-johans asked about the original issue - the original issue was filed by @lspiro-Tick42  
  - Next steps - feedback from participants in the standard working group. 
  - @dimiter-georgiev asked the group if anyone felt anything is missing, there were no vocal points in the meeting for missing items.

## Action Items
- [ ] @all Asks for other vendors that may use this type (`fdc3.order`) to ensure there is an agreement with #824 
- [ ] Container Vendors to work up an example for notifications via intents and contexts @kriswest and @dimiter-georgiev have suggested they could work together to create a working example based on #828 
- [ ] @all feedback from participants in the standard working group regarding #828 
- [x] @pierreneu to raise an issue for working group to include extra optional information in `ContextMetadata` or otherwise pass additional metadata about a context.
- [ ] @milindchidrawar merge #747 and #761

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony

**Comment by WatsonCIQ** [comment]
Chris Watson / Cosaic 👋

**Comment by milindchidrawar** [comment]
Milind / Singletrack

**Comment by Julia-Ritter** [comment]
Julia / FINOS 👋

**Comment by luiemilio** [comment]
Luis / OpenFin

**Comment by openfin-johans** [comment]
Johan Sandersson / OpenFin 🎁

**Comment by greyseer256** [comment]
Hugh Troeger / FactSet
