### ISSUE TITLE
Standard WG Meeting - Oct 27th, 2022

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#838]
## Date
Thursday 27 Oct 2022 - 10am EST / 3pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system:
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from the previous meeting (5mins)
  - #818
- [x] Call for contributions: FINOS App Directory (5mins)
- [x] Discussion of open issues (40mins)
  (will not get to all, the remainder to roll over to future meetings):
  - [x] #825
  - [x] #827 
  - [x] #829
  - [x] #832 
  - [x] #811
  - [x] #841 
  - [x] #833
    - #834
    - #842
  - [ ] #242
  - [ ] #301 
  - [ ] #559 
  - [ ] #563
  - [ ] #735 
  - [ ] #386 
  - [ ] #387
  - [ ] #564
- [x] AOB & Adjourn (5mins)
  - Please raise issues for any topic that you'd like discussed at future meetings. 

## Minutes
- @robmoffat provided a demo of the draft FINOS app directory and website https://directory.fdc3.finos.org/
- #825
  - There was consensus that the Standard does allow for dynamic registration of intent handlers at runtime as an optional feature (MAY), while apps SHOULD be registered via appD Configuration.
  - The wording used should be clarified with compliance keywords and, perhaps, referred to from the raiseIntent/findIntent functions docs.
  - PR to be raised to update 2.0 and next documentation.
- #827 
  - Error responses are in fact defined for v2 routes, but they're missing response samples which makes them less obvious. Response samples should be added to the OpenAPI spec. 
- #829
  - @pierreneu gave an overview of the use case for being able to pass supplementary context for the source of an interaction within an application that raises an intent:
    - For example, a chat message might contain a button to raiseIntent to ViewChart or ViewNews etc. with a specified fdc3.instrument context, additional context would identify what ChatRoom that came from to enable targeting of any messages sent in reply.
    - I.e. the intention is to enable any secondary or response actions to be better targeted or specified - without changing the context type that is sent to a Symphony or chat integration specific type (which might cut down the number of apps available to process the intent, as they require specific context types).
  - @kriswest provided a summary of a proposed solution (posted on the issue), involving adding additional optional parameters to broadcast and raiseIntent calls to supply the additional context and then delivery of that [context/intentHandlers](https://fdc3.finos.org/docs/api/ref/Types#contexthandler) at the destination via a new field in the optional [`ContextMetadata`](https://fdc3.finos.org/docs/api/ref/Metadata#contextmetadata) object they can receive in 2.0.
  - @nkolba observed that this could also be solved by decorating context types with additional fields - which is similar to how the `id` field is handled which is open, allowing many different identifiers to be added.
    - @nkolba observed that this route has the advantage of not requiring changes to the Desktop Agent API, only the context types/schemas. 
    - In discussion, @kriswest observed that this is workable, but might promote non-standard structures/variation in context types and that, if we go this route, we could standardize a location in the base `Context` type additional source metadata.
      - However, @kriswest also observed that the `ContextMetadata` contains the `AppIdentifier` for the source application, which is provided by the DesktopAgent to prevent spoofing. The additional metadata we are looking to provide is relative to / supporting that information (as you would, for example, want to target an intent to reply at the chat application (using the `AppIdentifier` and provide the chatRoom context to deliver it to the right room within the application, so it would make sense to keep these together.
  - Consent was sought to start moving proposals to PRs - both @nkolba and @kriswest expressed an interest in working on proposals.
- #832 
  - @robmoffat provided an overview of the OpenSSF badging effort, intended to promote best practices in OS projects - as well as the [FINOS security scanning tools](https://github.com/finos/security-scanning) being applied to the FDC3 repo in PR #808 
  - FDC3 currently achieves a 99% score - to achieve 100% it needs to have a unit testing policy and code coverage tests ensuring that code coverage always increases with changes.
  - @kriswest gave an overview of software delivered by FDC3 (NPM module, FDC3 Workbench, FDC3 Explained, website), current testing (NPM module only) and known issues (vulnerabilities in FDC3 workbench dev server, website, semgrep identified issue in FDC3 Explained and typegen code used for NPM module).
     - FDC3 workbench needs updating to latest react scripts as part of maintenance
     - typegen solution in NPM module needs updating
     - FDC3 Explained needs a small code change to mitigate
     - website needs upgrading to docusaurus v2
   - FDC3 maintainers to investigate code coverage scanning and raise a PR to add a unit testing policy to governance, with repository restrictions based on codecoverage testing (must not decrease).
- #811
  - Semgrep failure in FDC3 Explained requires a code change to resolve. @openfin-johans to try and find someone to resolve - fallback to @kriswest and @WatsonCIQ if necessary.
- #841 
  - As discussed at #839, the wording of findIntent's docs is less clear that the NoAppsFound error should be returned rather than an AppIntent with an empty `apps` array
    - @nkolba would seem a valid and normal response  
      - @nkolba the metadata could come from the appD if we add the proposed /intents endpoint #719.
      - However, symmetry with `raiseIntent` functions may be more useful
    - @kriswest having two interpretations promotes variation and makes compliance testing harder. I believe the error is what was intended as the `AppIntent` metadata had to be retrieved from apps in the past (although we are deprecating that under #312).
    - Consent was sought and received to clarify the wording in the 2.0 and next documentation to specify that the error should be returned.
- #833
  - Error in Context schema and types generated for it (that appear in NPM module)
  - PR #834 raised by @mistryvinay to resolve
  - PR #842 raised by @kriswest to regenerate types (as this didn't happen automatically) and to release an updated NPM module
  - @bingenito commented that he was willing to take this on (which is much appreciated!) however documentation of how to handle type generation / prepare an NPM module release for FDC3 is not provided.
  - @kriswest remarked that work on the typegen system is needed (both updating deps and implementing a solution for #749 to help release new context and intent types on adoption, without waiting for a new FDC3 version to be released).

### Decisions Made
- ...

## Action Items
- [x] @kriswest prep next meeting agenda to include next issues on list
- [x] @pgn-vole @kriswest Raise a PR to resolve #825
  -  clarify (with compliance keywords) the Standard's support for dynamic registration of intent handlers for use in a resolver.
  - #844 
- [ ] @kriswest Raise a PR to resolve #827
 - Add error response samples to appD v2 API routes to make them more obvious in the Swagger spec for appD.
- [ ] @kriswest @nkolba @pierreneu to work on proposals/PRs demonstrating possible solutions to #829. These should include example use-cases demonstrating the need for and utility of the revision
- [ ] @finos/fdc3-maintainers to investigate adding code coverage scanning to repo and to propose a unit testing policy/raise a PR to add to governance and resolve #832.
- [ ] @openfin-johans find a volunteer to help resolve #811 - fallback to @kriswest and @WatsonCIQ if necessary
- [x] @kriswest of volunteer: raise PR to resolve #841
  - Clarify findIntent function docs to specify `ResolveError.NoAppsFound` error when no apps are found.
  - #843
- [ ] @finos/fdc3-maintainers to review #842 to enable NPM module release  
  

Rolled over from previous meetings:
- [ ] @kriswest or volunteer: raise PR to resolve #719 
  - Add optional/recommended API endpoints for /intents and /contexts to the appD API.
- [ ] @kriswest or volunteer: raise PR to resolve #312 
  - deprecate `interop.intents.listensFor[<intentname>].displayName` field in appD and `AppIntent.intent.displayName` in the API types and add explanation of using intent name for display to documentation.
- [x] @kriswest or volunteer: raise a PR to resolve #807
  - Clarify (in the 2.0 version of the documentation) that FDC3 API calls the result in errors should reject with an Error object, rather than a String.
  - #843
- [ ] @kriswest or volunteer: raise a PR to resolve #820
  - Make `name` optional and deprecated in appD records and making `title` required. 

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by milindchidrawar** [comment]
Milind / Singletrack

**Comment by openfin-johans** [comment]
Johan Sandersson / OpenFin 🎁

**Comment by pierreneu** [comment]
Pierre Neu / Symphony

**Comment by luiemilio** [comment]
Luis Espinola / OpenFin

**Comment by dimiter-georgiev** [comment]
Dimiter Georgiev / Symphony

**Comment by bingenito** [comment]
Brian Ingenito / Morgan Stanley

**Comment by timjenkel** [comment]
Tim Jenkel / Wellington

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by MichaelMCoates** [comment]
Michael Coates / OpenFin

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony

**Comment by robmoffat** [comment]
Security scanning tools being used at FINOS: https://github.com/finos/security-scanning
