### ISSUE TITLE
Standard WG Meeting - Nov 30th, 2022

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#867]
## Date
Wednesday 30 Nov 2022 - 10am EST / 3pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system:
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call, review meeting notices (5mins)
- [ ] Review action items from previous meeting (5mins)
- [ ] [OSFF NY Thursday 8th December](https://events.linuxfoundation.org/open-source-finance-forum-new-york/) (2mins)
- [ ] Update on FDC3 Conformance testing project progress (5mins)
- [ ] Discussion of open issues (40mins)
  (will not get to all, the remainder to roll over to future meetings):
  - [ ] #866
  - [ ] #242
  - [ ] #301 
  - [ ] #735 
  - [ ] #564
  - [ ] #386 
  - [ ] #387
  - [ ] #559 
  - [ ] #563
- [ ] AOB & Adjourn (3mins)

## Minutes
- ...

### Decisions Made
- ...

## Action Items
- [ ] ...

Rolled over from previous meetings:
- [ ] @kriswest Raise a PR to resolve #827
 - Add error response samples to appD v2 API routes to make them more obvious in the Swagger spec for appD.
- [ ] @kriswest @nkolba @pierreneu to work on proposals/PRs demonstrating possible solutions to #829. These should include example use-cases demonstrating the need for and utility of the revision
- [ ] @finos/fdc3-maintainers to investigate adding code coverage scanning to repo and to propose a unit testing policy/raise a PR to add to governance and resolve #832.
- [ ] @openfin-johans find a volunteer to help resolve #811 - fallback to @kriswest and @WatsonCIQ if necessary
- [ ] @finos/fdc3-maintainers to review #842 to enable NPM module release  
- [ ] @kriswest or volunteer: raise PR to resolve #719 
  - Add optional/recommended API endpoints for /intents and /contexts to the appD API.
- [ ] @kriswest or volunteer: raise PR to resolve #312 
  - deprecate `interop.intents.listensFor[<intentname>].displayName` field in appD and `AppIntent.intent.displayName` in the API types and add explanation of using intent name for display to documentation.
- [ ] @kriswest or volunteer: raise a PR to resolve #820
  - Make `name` optional and deprecated in appD records and making `title` required. 
  
  
## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by kriswest** [comment]
Kris West / Cosaic 🚀

**Comment by novavi** [comment]
Derek Novavi / S&P Global

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by timjenkel** [comment]
Tim / Wellington

**Comment by pierreneu** [comment]
Pierre Neu / Symphony

**Comment by robmoffat** [comment]
Rob/ FINOS

**Comment by greyseer256** [comment]
Hugh / FactSet
