### ISSUE TITLE
Standard WG Meeting - Jan 26, 2023

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#899]
## Date
Thursday 26 Jan 2023 - 10am EST / 3pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system:
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
- [x] Announcements: (5mins)
  - Update to FDC3 workbench (1 deployed, 1 about to be, 3rd waiting in the wings) 
  - FDC3 Hackathon in New York at the end of March
- [x] FDC3 2.1 Roadmap and timeline (3mins)
- [x] Discussion of open issues (40mins)
  (will not get to all, the remainder to roll over to future meetings):
  - [x] (new) #889
  - [x] (new, conformance/docs) #871
  - [x] (new, conformance/docs) #872
  - [x] #735
  - [x] (new) #896
  - [ ] Issues that _may_ relate to container APIs or config
    - [ ] #564
    - [ ] #386 
    - [ ] #387
  - [ ] #559 
  - [ ] #563
- Adjourn (2mins)

## Minutes
- Update to FDC3 workbench:
  - Deployed: 
    - AppChannels supported
    - Reworked context handling, custom templates saved to local storage, basic intent targeting
  - Due to be deployed:
    - Switch from create-react-app to vite.js (better maintained, resolves  vulnerable dependencies)
  - PR due to be raised for full set of 2.0 features.

- FDC3 Hackathon in New York at the end of March
  - Input sought from community on topics/challenges
  - Help running Hackathon desired
  - get in touch with rob.moffat@finos.org

- FDC3 2.1 Roadmap and timeline
  - Roadmap has yet to be filled out, likely inclusions:
    - Batch of intents & contexts from discussion group
    - Desktop Agent Bridging
    - A number of docs clarifications
    - Accrued action items from these meetings (see action items)
  - Maintainers suggestion is that we try to establish candidate scope at February meeting (issues should be raised by then), with PRs due by April meeting, Adoption Vote in May/June in time OSFF in London.
  - Volunteers sought to help with outstanding PRs and maintenance tasks - maintainers happy to provide introduction to contributing
  
- #889
  - An introduction to this issue, and how it might help drive adoption of FDC3 and comprehension amongst users of what action will be taken when clicking on a control, was provided by @pierreneu 
  - A number of participants spoke in support of the issue including @nkolba @lspiro-Tick42 and @kriswest
  - It was proposed that a discussion group, or at least a special meeting, is convened to move this forward.
  - It was requested that interested parties post on the issue to indicate willingness to participate and that an email is sent to the fdc3@finos.org mailing list to help recruit participants.
    
- #871
  - Those collaborating on the conformance tests believe this needs further clarification in documentation.
  - As the proposal is to simply clarify existing behavior, this can and should be done in past, current and future FDC3 docs versions
  - Consent was sought and received to implement the necessary PR

- #872 
  - Those collaborating on the conformance tests believe this needs further clarification in documentation.
  - As the proposal is to introduce new behavior (which may be conformance tested) it should only be implemented in future FDC3 versions
  - Consent was sought and received to implement the necessary PR for inclusion in the 2.1 scope

- #735
  - Discussion of this issue was carried over from previous meetings and there is general consensus that it needs further thought
    - Is it more important
  - @lspiro-Tick42 suggested that the change should be made, but with a strong caveat in the documentation that the data provided is only as trusted/trustworthy as the Desktop Agent AND App Directory that provided it with the data
  - @nkolba suggested that more thought needs to be put into trust relationships in FDC3, between apps and apps and the DA
    - In discussion it was determined that trust in the AppD also needs to be considered, particularly if its used to host any form of ID validation data.
    - @nkolba also suggested that there might be a way to anonymously check identity/trust through an exchange of token/validation of those.
  - @kriswest suggested that this issue overlaps with FDC3 on the Web (next item on agenda) to a degree and might make sense to discuss alongside how apps running in a browser might discover and load a DA client library
  - The discussion was curtailed, but should continue at a further meeting

- #896
  - @kriswest opened discussion with: 
    - A brief summary of the issue - which has already begun with a lively discussion over email (see https://groups.google.com/a/finos.org/g/fdc3/c/jCvlLjokBLs/m/TBoK6lZYAQAJ)
    - Apology that some participants did not receive all emails referred to in the thread 
    - Proposal that, as this is an important, interesting and contentious issue that we set-up a discussion group to look at proposals to bring back to the SWG (poll to be raised for first meeting date)
  - @nkolba suggested that the discussion conflates 3 issues that should be dealt with separately
    1. Should the window.fdc3 global be required (as it is in 2.0, recommended only in 1.2)
    2. Do we need to do more to enable FDC3 on the Web
    3. Should the FDC3 conformance tests for 1.2 be requiring the global (as they currently do).
  - Regarding 3, @kriswest indicated that the documentation allows module imports in 1.2 (and that he'd previously thought they were not - the change was made prior to 2.0, but deferred as breaking to 2.0) and hence it could, however, there was also the challenge that custom code/bootstrapping has to be added to the conformance framework and each of its mocks for each implementation with a module import, which is obviously undesireable and an example of the problem that the lack of standardized method of loading such an implementation causes.
  - Regarding 1 and 2, @kriswest indicated that he and others believed these issues to be intrinsically linked and need dealing with together.
  - Consent was sought and received to set up a discussion group to continue examination of the issue and proposals to resolve - a poll should be posted for the first meeting time (at a time suitable for both US and UK participants).

## Action Items
- [x] @pierreneu to send an introduction to issue #889 to the fdc3@finos.org mailing list to help recruit collaborators. Maintainers/FINOS to support setup of a meeting to discuss afterwards.
- [ ] @kriswest or volunteer: raise PR to resolve #871
- [ ] @kriswest or volunteer: raise PR to resolve #872
- [x] @kriswest to post a poll for date/time of a first meeting of a discussion group to address FDC3 on the Web (+trust relationships/originating app metadata) 
- [ ] Participants with use cases that require multiple or directional channel membership to post details on issue #242 to inform future discussion.
    
Rolled over from previous meetings:
- [ ] @kriswest or a volunteer, Raise a PR to resolve #866
  - Add: 
    - a recommended maximum time after start-up within which apps SHOULDadd context and intent listeners
    - a required maximum time after start-up within which apps MUST add context and intent listeners
    - statement that Desktop Agents MAY be configured to extend timeouts applied to `open` or `raiseIntent` functions.
- [ ] @kriswest Raise a PR to resolve #827
 - Add error response samples to appD v2 API routes to make them more obvious in the Swagger spec for appD.
- [ ] @kriswest @nkolba @pierreneu to work on proposals/PRs demonstrating possible solutions to #829. These should include example use-cases demonstrating the need for and utility of the revision
- [ ] @finos/fdc3-maintainers to investigate adding code coverage scanning to repo and to propose a unit testing policy/raise a PR to add to governance and resolve #832.
- [x] @openfin-johans find a volunteer to help resolve #811 - fallback to @kriswest and @WatsonCIQ if necessary
- [ ] @finos/fdc3-maintainers to review #842 to enable NPM module release  
- [ ] @kriswest or volunteer: raise PR to resolve #719 
  - Add optional/recommended API endpoints for /intents and /contexts to the appD API.
- [ ] @kriswest or volunteer: raise PR to resolve #312 
  - deprecate `interop.intents.listensFor[<intentname>].displayName` field in appD and `AppIntent.intent.displayName` in the API types and add explanation of using intent name for display to documentation.
- [ ] @kriswest or volunteer: raise a PR to resolve #820
  - Make `name` optional and deprecated in appD records and making `title` required. 
  

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by tpina** [comment]
Tiago Pina / Finsemble

**Comment by milindchidrawar** [comment]
Milind Chidrawar / Singletrack

**Comment by nkolba** [comment]
Nick Kolba / Connectifi

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony

**Comment by kriswest** [comment]
Kris West / Finsemble 🚀

**Comment by novavi** [comment]
Derek Novavi / S&P Global

**Comment by WatsonCIQ** [comment]
Chris Watson / Finsemble 👋

**Comment by timjenkel** [comment]
Tim / Wellington

**Comment by sebbenmbarek** [comment]
Seb Ben M'Barek / NORMAN & SONS

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by Julia-Ritter** [comment]
Julia  / FINOS

**Comment by pierreneu** [comment]
Pierre Neu @ Symphony

**Comment by openfin-johans** [comment]
Johan Sandersson / OpenFin 🎁

**Comment by lspiro-Tick42** [comment]
Leslie / Tick42

**Comment by pbaize** [comment]
Pierre Baize / OpenFin
