### ISSUE TITLE
Standard WG Meeting - Feb 23rd, 2023

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#913]
## Date
Thursday 23rd Feb 2023 - 10am EST / 3pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system:
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #899 
- [x] Announcements: (10mins)
  - **FDC3 Training and Certification for 2.0**
    - #895
    - #909
  - **FINOS Hackathon in New York**
    -  A FINOS Hackathon is a 2 full-days in-person event, open to all developers employed (or sponsored) by a  FINOS member  that aims to provide venues to get together, code, learn and - most importantly - have fun , with the mission to  collaborate and innovate to help solving real life problems in the financial space.
    - **Topics**:
      - Desktop Interoperability  - Build solutions to seamlessly  integrate multiple applications across the desktop, using open source technologies and standards, such as FDC3. 
      - Open RegTech  - Explore and promote opportunities for  open collaboration between 
 financial institutions, technology firms, service providers and regulators. 
    - **When and where** 
      BMO Capital Markets - 151 West 42nd Street, New York 
      Starts on May 3rd at 1.30pm EST 
      Ends on May 4th at 6pm EST
  - **FDC3 conformance 2.0**
  - **FDC3 2.1 Roadmap reminder**
    - [Milestone: 2.1 candidates](https://github.com/finos/FDC3/milestone/6)
- [x] **Discussion of open issues** (40mins)
  - [x] #904 
    - Call for contributions to use cases/intents
    - Next CD & I meeting 2nd March 2023
  - [x] #900
  - [x] #883
    - Correct entries with `String` rather than `string`?
  - [x] Trust and authentication in FDC3
    - Prompted by #735
    - What are the current trust relationships
    - What could/should we improve
    - Is there consensus to make the change proposed by #735 now or after further work?
  - [ ] Issues that _may_ relate to container APIs or config
    - [ ] #564
    - [ ] #386 
    - [ ] #387
  - [ ] #559 
  - [ ] #563
- [x] **AOB & Adjourn** (5mins)
  - See recent Discussion group meetings:
  - #903
    - Next meeting: 2nd March 2023
  - #911
    - Next meeting: 22nd March 2023
  - #908 
    - Contributions welcome on #896
    - Next meeting: 2nd March 2023

## Minutes
- **FDC3 2.1 Roadmap reminder**
  - [Milestone: 2.1 candidates](https://github.com/finos/FDC3/milestone/6)
  - Raise any issues for inclusion ASAP, comment on issues in milestone, ensure PRs are raised by April meeting
- #904 
  - Initial work on Order/Trade/Position context types stalled when the level of detail became excessive
    - Whereas for most usecases only very light details are needed such as an ID or security.
    - Hence, we're rethinking and trying to gather use-cases to workshop at the next CD&I meeting.
    - With the intention of adding a simple set of contexts and intents to support them, which can then be expanded as the need (and use-cases) arise. 
- #900
  - Participants had rarely seen this element used - and it is not exposed via teh FDC3 API anywhere, so its not currently usable by an app unless a container implements custom support for it.
  - However, there may be a use-case for being able to set config that is retrievable through the FDC3 API, rather than having to set it individually for each container.
    - @robmoffat 
      - > I have tried to use this, but since the apps don't have access to this via their metadata, it seems like it's redundant. It would be really handy if this was a way for the app directory to pass config to the app.
         I would be very pleased to see this added to ImplementationMetadata
         Some use cases:
         > - I could configure some endpoints in the app to say what data sources It talked to
         > - I could set up some preferences in the app to say how I want the app to be used
- #883
  - Author's issues have been answered and code generation was largely correct, including TS overloads
  - However, author is correct that FDC3 Types (incorrectly) use `String` in some places rather than `string`?
    - A new issue should be raised to correct this in 2.0 and future versions
- **Trust and authentication in FDC3**
  - Prompted by #735
    - Desktop agent is providing identity from one app to another app
    - But its only as trusted as your desktop agent
    - A participant asked if making originating app metadata required would introduce complexities in getting started in FDC3, as the more requirements we have more, the more difficult it becomes to implement
      - Its only a requirement on the desktop agent rather than an app, so it doesn't make it harder to get started for app developers
    - Container trust relationship. End user is running it on their desktop 
      - Once we support FDC3 in a browser there are wider issues to be considered as the trust relationship changes - its is no longer User -> DA vendor, but rather Apps -> DA vendors.
    - Defer a decision on #735 until our next meeting and also refer to the FDC3 for Wb Browsers group to discuss.
  - Does FDC3 need to be able to support more authentication (of App or DAs, by Apps or DAs?)

- #564
  - FDC3 has always been scoped down to not worry about window sizing
  - Should we draw a few things in the app d setting to include window information
    - Defining size and position
    - Propose basic window settings
  - No strong opinions expressed by attendees.

## Action Items
- [x] @kriswest Close #883 and raise a new issue and PR to correct FDC3 API types that use `String` rather than `string`
- [ ] @kriswest Refer questions about the need for more 'authentication' in FDC3 to FDC3 for Web Browsers group
- [x] @robmoffat check with FINOS board about their thoughts on/requests for authentication in FDC3 - specifically what should be authenticated/authenticable and by whom.
- [ ] Participants with use cases that require multiple or directional channel membership to post details on issue #242 to inform future discussion.

Rolled over from previous meetings:
- [ ] @kriswest Raise a PR to resolve #827
  - Add error response samples to appD v2 API routes to make them more obvious in the Swagger spec for appD.
- [ ] @kriswest @nkolba @pierreneu to work on proposals/PRs demonstrating possible solutions to #829. These should include example use-cases demonstrating the need for and utility of the revision
- [ ] @finos/fdc3-maintainers to investigate adding code coverage scanning to repo and to propose a unit testing policy/raise a PR to add to governance and resolve #832.
- [ ] @finos/fdc3-maintainers to review #842 to enable NPM module release  
- [ ] @kriswest or volunteer: raise PR to resolve #719 
  - Add optional/recommended API endpoints for /intents and /contexts to the appD API.
- [x] @kriswest or volunteer: raise PR to resolve #312 
  - deprecate `interop.intents.listensFor[<intentname>].displayName` field in appD and `AppIntent.intent.displayName` in the API types and add explanation of using intent name for display to documentation.
- [x] @kriswest or volunteer: raise a PR to resolve #820
  - Make `name` optional and deprecated in appD records and making `title` required. 
- [ ] @kriswest or a volunteer, Raise a PR to resolve #866
  - Add: 
    - a recommended maximum time after start-up within which apps SHOULDadd context and intent listeners
    - a required maximum time after start-up within which apps MUST add context and intent listeners
    - statement that Desktop Agents MAY be configured to extend timeouts applied to `open` or `raiseIntent` functions.
- [ ] @kriswest or volunteer: raise PR to resolve #871
- [ ] @kriswest or volunteer: raise PR to resolve #872

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by tpina** [comment]
Tiago Pina / Finsemble

**Comment by WatsonCIQ** [comment]
Chris Watson / Finsemble 👋

**Comment by novavi** [comment]
Derek Novavi / S&P Global

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by timjenkel** [comment]
Tim / Wellington

**Comment by kriswest** [comment]
Kris West / Finsemble

**Comment by greyseer256** [comment]
Hugh Troeger / FactSet

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony

**Comment by sarahstone-cosaic** [comment]
Sarah Stone / Finsemble

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by openfin-johans** [comment]
Johan / OpenFin 🎁

**Comment by mattjamieson** [comment]
Matt / WhiteDog
