### ISSUE TITLE
Context Data & Intents Discussion group - 2 Mar 2023

### ISSUE THREAD

**Issue by mistryvinay** [finos/FDC3#916]
## Group overview
At the FDC3 Use Cases Roundtable London, October 5th 2021 participants agreed that the FDC3 lexicon needs to be expanded, both with additional intents and context types to support Use Cases, but also to include more primitive data types in order to construct complex types. A number of participants also agreed that now is an appropriate time to expand the Lexicon.
​
See https://github.com/finos/FDC3/issues/455 for full details of the meeting outcomes.
​
This group is being convened to discuss and arrange work to contribute further Context types and Intents to support Use Cases being implemented by participants.

### Relevant issue tags
Current open issues that relate to the discussion group: 
[![image](https://user-images.githubusercontent.com/1701764/139841356-416d9276-81f5-4fce-b5d8-f856d4bda855.png)](https://github.com/finos/FDC3/labels/Context%20Data%20%26%20Intents)

Issues will also be tagged with the labels:
[![image](https://user-images.githubusercontent.com/1701764/139841631-c6bf8697-fafe-4266-8552-63a648625e8b.png)](https://github.com/finos/FDC3/labels/context-data)
[![image](https://user-images.githubusercontent.com/1701764/139841690-969a9d14-a0aa-44a7-bdfe-8c4a43ad30d9.png)](https://github.com/finos/FDC3/labels/intents)

## Meeting Date
Thursday 2 Mar 2023 - 9am EST / 2pm GMT

### WebEx info
- Meeting Link: https://finos.webex.com/finos/j.php?MTID=mbb193ae433ce8d4366adcecd94355734
- Meeting number: 2556 257 8293

*More ways to join*
- Join by video system:
   - Dial 25562578293@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2556 257 8293

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - [x] #903 
- [x] Discussion of open issues (30mins)
  - [x] #872 
  - [x] #904 
- [x] Issues requiring a PR (10mins)
  - [ ] #828 
  - [ ] #856 
- [x] PR's ready to merged into 2.1 Milestone release (3mins)
  - #747 
  - #761 
  - #824 (*experimental label)
  - #869 
  - #875 
  - #882 
- [x] AOB & Adjourn (5mins)

## Minutes
- #872 
  - Looking for volunteers to turn this into a PR
- #904
  - ViewParent/ ViewChildren:  Use ViewOrder, an EMS should have details of the parent order already
    - @nemery-flextrade: Order is (in my head) and entry in the OMS, although the EMS will also have  record for it. The linkage between the should always be available. Use ViewOrder (with an order object) for EMS -> OMS.
      - However, OMS may not be aware of individual trade ids to go the other way...
      - Do we need a type for an execution? There are two levels to an order: OMS order -> multiple EMS orders or trades, which might have multiple executions.
      - @kriswest we need to create names where the action that will be taken is instantly recognizable....
        - If in your OMS you raise ViewOrder and presented with the EMS as an option do you understand what will happen?
        - If in your EMS you raise ViewOrder and presented with the OMS as an option do you understand what will happen?
        - @timjenkel: We use order for the OMS, placements for the EMS, but have heard tickets (although more often refers to allocation tickets)
      - Placements would be understood by most for placement of an order with a broker or a venue
    - Proposal agreed:
      - ViewOrder for OMS -> EMS
      - ViewPlacement for EMS -> OMS
        - @mistryvinay
        - @nemery-flextrade: ViewOrderTickets overlaps with order entry dialogs and allocations. Placements might be less ambiguous
    - @nemery-flextrade: Consider replacing Trade, with a Placement context type in that case. While an order and placement will have a lot of overlap in terms of field (instrument, side) - there will be differences (destination, venue, strategy on a Placement).
      - @kriswest: Semantics of having a different type value are also useful alone.
  - `ModelTrade`
    - @nemery-flextrade: agree with use case, but think the name could be clearer.
      - The use case relates more to a position than an order.
    - @kriswest, should use prefixes from spec
      - @nemery-flextrade: StartModelTrade?
      - @timjenkel: What about CreateOrder - seems related to creating an order from a position
        - @nemery-flextrade: Seems like CreateOrder would be a second step after the modelling.
        - Refer back to @domgifford to comment.
  - @timjenkel: Use cases for showing pre-trade analytics, quotes etc. ViewAnalysis, ViewChart, ViewQuote
    - Select order in OMS, select remote application to process
    - Remote app may not have the order id in this case
      - Some will definitely need additional details: e.g. quantity, instrument
    - `ViewChart`
      - Pre-trade: a trade schedule, rather than pricing chart, Order context needs:
        - (no id avail)
        - Instrument
        - Quantity
        - Side
        - SettlementDate
      - Inflight orders: pricing chart, with trades, volume charts or pricing chart with volume indicators, Order context needs:
        - Id for the order (maybe)
        - Instrument
        - Quantity
        - Side
        - SettlementDate
        - Trades or Executions?
    - `ViewAnalysis`
      - Pre-trade or post-trade analytics or other analysis - exact details depend on app its sent to
      - Same order details as previous examples
      - Again needs an optional set of executions, Execution could have
        - price
        - side
        - quantity
        - exchange
        - consider an unstandardized block to put in the many other things, like fix executions:
        - executionCapacity?
        - execution venue liquidity indicators?
        - various regulatory stuff
    - `ViewQuote`
      - May wish to view a specific quote
      - @timjenkel Existing accepts Instrument
        - Extend to add order context type
      - May want to see existing quotes for an order, or retrieve new quotes
      - @nemery-flextrade due to MiFiD you have to have multiple quotes for your orders, but you might not need to retrieve them all at the same time/from same app
      - @timjenkel Pluralisation doesn't matter
      - @kriswest: What about other prefixes to indicate different actions
        - @nemery-flextrade: StartQuote (start filling in a quote form), CreateQuote (interacting with an automated system to create quotes), GetQuote (retrieve quotes associated with an Order)
      - @nemery-flextrade: makes sense for all to accept Order, Also need a Quote type for return data or looking up a specific quote
  - Need to create a `Quote` context
    - Instrument
    - Settlement date
    - Side
    - Quantity
    - Price
    - Price basis (spread, par etc.)
    - Quote source: Organization or Contact
  - `StartOrder` or `CreateOrder`
    - Might follow on from StartTradeModel
    - Will want trader to take a last look before creation so prefer StartOrder to CreateOrder, so not straight record creation
  - `StartPlacement`
    - @nemery-flextrade: A system might give you recommendations of how to slice an order in placements
    - Trader will need last look before it goes out so prefer Start to Create
    - Contexts: could be Order or Placement
    - Order as previous examples - though it might be just order id if EMS has details, however if creating from a pre-trade analysis will need additional fields from previous examples
    - Placement type would need:
      - link to Order or Quote

## Action Items
- [ ] Volunteers for creating a PR for #872 
- [ ] @kriswest request to raise a PR for #828 
- [ ] @kriswest to reach out to ChartIQ team for a PR for #856 
- [ ] @nemery-flextrade Create branch for new PR's relating to new Context types described above (#904 )

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by kriswest** [comment]
Kris West / Finsemble 🚀

**Comment by nemery-flextrade** [comment]
Nathan / FlexTrade

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony

**Comment by Julia-Ritter** [comment]
Julia / FINOS 👋

**Comment by mistryvinay** [comment]
Vinay Mistry / 🎵
