### ISSUE TITLE
Standard WG Meeting - March 23, 2023

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#934]
## Date
Thursday 23rd March 2023 - 10am EDT / 2pm GMT (Note daylight savings time in US but NOT UK)

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system:
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
    - #913
- [x] **Announcements: (5mins)**
    - FINOS Hackathon in New York
        -  A FINOS Hackathon is a 2 full-days in-person event, open to all developers employed (or sponsored) by a  FINOS member  that aims to provide venues to get together, code, learn and - most importantly - have fun , with the mission to  collaborate and innovate to help solving real life problems in the financial space.
        - Topics:
            - Desktop Interoperability  - Build solutions to seamlessly  integrate multiple applications across the desktop, using open source technologies and standards, such as FDC3. 
            - Open RegTech  - Explore and promote opportunities for  open collaboration between 
 financial institutions, technology firms, service providers and regulators. 
        - When and where 
            BMO Capital Markets - 151 West 42nd Street, New York 
            Starts on May 3rd at 1.30pm EST 
            Ends on May 4th at 6pm EST
    - Help FINOS build a certification for FDC3 professionals!
        - https://share.hsforms.com/1jgeYsjC-T7CYXq7bRQC6Iw1fux8
    - FDC3 2.1 Roadmap reminder
        - [Milestone: 2.1 candidates](https://github.com/finos/FDC3/milestone/6)
- [ ] **Update on FDC3 Training Course** from @mistryvinay (Symphony) and @jimbunting (Finsemble) (10mins)
    - #895
- [x] **FDC3 2.1 PRs (5mins)**
    - Open PRs:
        -  #915 
            - #924 
        - #312 
            - #916 
        -  #820 
            - #928 
        - #855 
            - #875 
        - #852 
            - #869 
  - PRs needed:
      - #674
      - #719
      - #735
      - #746 
      - #749 
      - #827
      - #828
      - #856
      - #866 
      - #871
      - #872
      - #921
- [x] **Discussion of open issues** (25mins)
    - [x] (briefly) revisit #900
    - [x] #931  
    - Issues that _may_ relate to container APIs or config
        - [ ] #564
        - [ ] #386 
        - [ ] #387
    - [ ] #559 
    - [ ] #563
    - [ ] (revisit) Trust and authentication in FDC3
        - Prompted by #735
        - What are the current trust relationships
        - What could/should we improve
        - Is there consensus to make the change proposed by #735 now or after further work?
- [ ] **AOB & Adjourn** (5mins)
    - See recent Discussion group meetings:
        - #916
            - Next meeting: 6th April 2023
        - #930 
            - Next meeting: 30th March 2023
        - DAB (if held 22nd March)
            - Next meeting: 26th April 2023

## Minutes
- A reminder was provided of the previously proposed timeline for FDC3 2.1:
    - Issues for inclusion should have already been raised
    - PRs should be raised by the April SWG meeting
    - Aiming for votes on inclusion to happen at the May SWG meeting
- Work has begun on the accumulated action items from previous meetings
    - Any volunteers wishing to participate in implementation should contact the FDC3 maintainers - contribution of PRs is the best place to start the journey of becoming an FDC3 maintainer.
- A reminder was provided that FINOS is recruiting SMEs and testers for the proposed FDC3 practitioner certification program - see: https://share.hsforms.com/1jgeYsjC-T7CYXq7bRQC6Iw1fux8
- #900
    - @kriswest asked if any participants want to speak for or against the proposed change (to make customConfig accessible to applications) - however, no one present wished to.
      - Hence, @kriswest recommended that we return to the originally suggested change: deprecate and later remove customConfig from the appD record (as it inaccessible to apps through the FDC3 API and proprietary mechanisms should probably stick to working through `hostManifests`). 
- #931 
    - @bingenito provided an overview of his approach to producing standardized interfaces for the FDC3 desktop agent API and standardized context types in .NET
        - [Main .NET standard library](https://github.com/morganstanley/fdc3-dotnet/tree/main/src/Fdc3) containing FDC3 interfaces, [context types](https://github.com/morganstanley/fdc3-dotnet/tree/main/src/Fdc3/Context), and some helper concrete implementations
        - [Json .NET standard library](https://github.com/morganstanley/fdc3-dotnet/tree/main/src/Fdc3.Json) that has helper methods leveraging Newtonsoft.Json for any required custom serialization (e.g. Pascal case to camel case or union types such as Email recipients).
    - The main library is based on hand-created, concrete types for context object, rather than JSON handling classes such as those provided by [Newtonsoft's JSON.net](https://www.newtonsoft.com/json) or [System.Text.Json](https://learn.microsoft.com/en-us/dotnet/api/system.text.json)
        - The primary library is mostly interfaces
        - a secondary library is provided with JSON helper functions that implement serialization/deserialization from classes implementing the interfaces - this separation ensures that the underlying JSON support can be implemented with whatever libraary/version is preferred.
    - @kriswest asked if @bingenito had encountered a use case for being able to swap the implementation of the desktop agent client out / dynamic loading of an implementation (as is possible with Javascript, enabling Write Once Run Anywhere [WORA])
        - Generally, no - most firms are using .Net apps internally rather than externally and hence on a specific desktop agent
            - The interfaces still have a lot of value without WORA - as does including them in the FDC3 standard
            - They provide a better pattern for implementation than interfaces based directly on JSON handling classes
            - Including them and maintaining them in the Standard will 'keep us honest' by forcing us to avoid or address early Typescript specific constructs, such as union types, that are difficult to replicate in other languages (a couple of union types already existing necessitate the use of marker interfaces in C# to achieve the same polymorphism)
    - a brief overview of the testing of the context types and serialization in the libraries (via validation of generated JSON via the published JSON schemas) was provided, e.g. https://github.com/morganstanley/fdc3-dotnet/blob/main/src/Tests/MorganStanley.Fdc3.Tests/Context/ChartTests.cs
    - @bingenito and @kriswest both recommended the inclusion of the interfaces in the main FDC3 project as they are not implementations (which would go into a separate software project) and they will be easier to test and maintain against the standard there.
    - @kriswest indicated that adding these to the Standard will require a fair amount of documentation work and project infrastructure work to publish a nuget package containing them - but also that this was a worthwhile endeavour
        - contribution of effort from firms that will benefit from these types will be sought.
    - @kriswest asked that the community begin review of packages provided and that we return to this topic at a future meeting to decide the issue
        - It was also indicated that this may not be at the next meeting which is likely to be focused on PRs for FDC3 2.1.
- Apology from @kriswest for inadvertently skipping over the training topic in the meeting agenda 😱 😞 

## Action Items
- [ ] #900 
    - @kriswest or a volunteer to update the issue with the discussion outcome and raise a PR deprecating `customConfig`
- [ ] #931 
   - Review of the proposed .NET interfaces by firms that will benefit from them is needed - along with a commitment to help with the update of the FDC3 documentation to include them.

Rolled over from previous meetings:
- [ ] @kriswest Refer questions about the need for more 'authentication' in FDC3 to FDC3 for Web Browsers group
    - referred but not yet discussed
- [ ] @kriswest Raise a PR to resolve #827
  - Add error response samples to appD v2 API routes to make them more obvious in the Swagger spec for appD.
- [ ] @kriswest @nkolba @pierreneu to work on proposals/PRs demonstrating possible solutions to #829. These should include example use-cases demonstrating the need for and utility of the revision
- [ ] @finos/fdc3-maintainers to investigate adding code coverage scanning to repo and to propose a unit testing policy/raise a PR to add to governance and resolve #832.
- [x] @finos/fdc3-maintainers to review #842 to enable NPM module release  
- [ ] @kriswest or volunteer: raise PR to resolve #719 
  - Add optional/recommended API endpoints for /intents and /contexts to the appD API.
- [ ] @kriswest or a volunteer, Raise a PR to resolve #866
  - Add: 
    - a recommended maximum time after start-up within which apps SHOULDadd context and intent listeners
    - a required maximum time after start-up within which apps MUST add context and intent listeners
    - statement that Desktop Agents MAY be configured to extend timeouts applied to `open` or `raiseIntent` functions.
- [ ] @kriswest or volunteer: raise PR to resolve #871
- [ ] @kriswest or volunteer: raise PR to resolve #872

### FDC3 2.1 TODO list
- **FDC3 2.1 PRs ready for review**
    -  #915 
        - #924 
    - #312 
        - #916 
    -  #820 
        - #928 
    - #855 
        - #875 
    - #852 
        - #869 
- **FDC3 2.1 PRs needed**:
      - #674
      - #719
      - #735
      - #746 
      - #749 
      - #827
      - #828
      - #856
      - #866 
      - #871
      - #872
      - #900
      - #921

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by chuck-adaptive** [comment]
Chuck Danielsson / Adaptive

**Comment by kriswest** [comment]
Kris West / Finsemble 🚀

**Comment by novavi** [comment]
Derek Novavi / S&P Global

**Comment by carmenmassbaum** [comment]
Carmen Massbaum - Wellington Management

**Comment by ColinEberhardt** [comment]
Colin / Scott Logic 🐱

**Comment by robmoffat** [comment]
Rob / FINOS 🤯

**Comment by hampshan** [comment]
Andrew Hampshire / UBS

**Comment by timjenkel** [comment]
Tim / Wellington

**Comment by mattjamieson** [comment]
Matt / WhiteDog
