### ISSUE TITLE
Context Data & Intents Discussion group - 6 Apr 2023

### ISSUE THREAD

**Issue by mistryvinay** [finos/FDC3#941]
## Group overview
At the FDC3 Use Cases Roundtable London, October 5th 2021 participants agreed that the FDC3 lexicon needs to be expanded, both with additional intents and context types to support Use Cases, but also to include more primitive data types in order to construct complex types. A number of participants also agreed that now is an appropriate time to expand the Lexicon.
​
See https://github.com/finos/FDC3/issues/455 for full details of the meeting outcomes.
​
This group is being convened to discuss and arrange work to contribute further Context types and Intents to support Use Cases being implemented by participants.

### Relevant issue tags
Current open issues that relate to the discussion group: 
[![image](https://user-images.githubusercontent.com/1701764/139841356-416d9276-81f5-4fce-b5d8-f856d4bda855.png)](https://github.com/finos/FDC3/labels/Context%20Data%20%26%20Intents)

Issues will also be tagged with the labels:
[![image](https://user-images.githubusercontent.com/1701764/139841631-c6bf8697-fafe-4266-8552-63a648625e8b.png)](https://github.com/finos/FDC3/labels/context-data)
[![image](https://user-images.githubusercontent.com/1701764/139841690-969a9d14-a0aa-44a7-bdfe-8c4a43ad30d9.png)](https://github.com/finos/FDC3/labels/intents)

## Meeting Date
Thursday 6 Apr 2023 - 9am EST / 2pm GMT

### WebEx info
- Meeting Link: https://finos.webex.com/finos/j.php?MTID=mbb193ae433ce8d4366adcecd94355734
- Meeting number: 2556 257 8293

*More ways to join*
- Join by video system:
   - Dial 25562578293@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2556 257 8293

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - [x] #916 
- [x] Discussion of open issues (30mins)
  - [x] #904 
  - [x] #940
- [x] Issues requiring a PR (10mins)
  - [x] #828 
  - [x] #856 
- [x] CD&I 2.1 consolidated PR (3mins)
  - [x] #936 
- [x] AOB & Adjourn (5mins)

## Minutes
- #904 
  - Simplified approach for defining Orders, Trade and Positions.
  - New proposed objects can be found here, #916 
  - Working with @nemery-flextrade for a PR submission 
- #940
  - Maintainers team broadly supportive for an easier and quicker way of adding Intents and Context more frequently. 
  - For each and every Context and Intent that is defined and created.  A PR is submitted back to the main standard.
  - Standard is only released periodically when we have a major milestone release like 2.0
  - Previous proposal of merging new additions by rolling the version number for a separate NPM module.
  - Still need to be conscious of the governance process around new submissions and voting into the Standard.
    - Since all parts of FDC3 were merged we only really do that once a year.
  - Or do we create a separate NPM module to handle additions.
    - Essentially whats on the FDC3/Overview pages defining Contexts and Intents as concepts stays in the Standard.
    - The actual specific types of Context and the specific Intent names do not really matter much versus the API versions.
      - You can make up any Intent or Context and you can use it with a version of the FDC3 API.
      - There's only a very light-tight restriction on Context.  It must have a type and it should have an Id field and name field if there's a display name or an any Id's involved.
      - Beyond that different versions of FDC3 do not need to know where the Intent and Contents came from
    - Would be nice to be able to move to a rolling basis where we release more frequently, say, every quarter.
    - That would involve separating the governance of these a little bit from the main FDC3 Standard, which contains the API's 
      - No need for a separate project or repository but rather a separate NPM module.
        - With the ability to vote on new additions which would be released in batches more frequently (every few months)
        - Also slight changes to website to separate out the specific lists of Intents and Context into a different area of the site thats not hooked to the Standards versions in the same way.
    - Proposal: Create a website or section of the website that is a Catalog of object definitions
      - Community can add PR's for new additions in to the catalogue
      - We can all see their definitions and a separate NPM module that contains types for them all.
      - Then publish incremental updates using semantic versioning e.g. v.1.0.0
      - This would be different from the current Standards version numbering.
      - Anything that is trying to change Intents and Context types as concepts would have to go back up to the FDC3 Standards working group.
      - Standardising types could be governed separately 
- #856
  - @dominicgifford do we want to overload the context object with object data
    - But rather with vendor specific payloads within them
    - Need to use standardised types so any chart provider can be used in workflows
    - @robmoffat proposal to make 'otherConfig' an array of context objects.
      - Encouraging use of standardised types and the establishment of areas for proprietary extensions within them.
      - If we've got a standardised type, you'll understand the top level of the object and a variable bits might be. And if those variable bits are typed, you can check them.
    - @kriswest prefers the standardisation of types
      - Place proprietary content within them using a patter like chart.otherConfig
      - Encouraging people to standardise and use published types.

## Action Items
- [ ] Volunteers for creating a PR for #872 
- [ ] @kriswest request to raise a PR for #828 
- [ ] @kriswest to reach out to ChartIQ team for a PR for #856 
- [ ] @nemery-flextrade Create branch for new PR's relating to new Context types described above (#904 )

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony 🎵

**Comment by jimbunting** [comment]
Jim / Finsemble

**Comment by Julia-Ritter** [comment]
Julia / FINOS w

**Comment by dominicgifford** [comment]
Dom / S&P
